// ---------------------------------------------------------------------------
// Portfolio Data — Auto-generated from portfolio-organized folder structure
// ---------------------------------------------------------------------------
export interface PortfolioCategory { id: string; label: string; photos: string[]; }
const IMG = "/images/portfolio-organized";
export const categories: PortfolioCategory[] = [
  { id: "curved-staircases", label: "Curved Staircases", photos: [
      `${IMG}/Staircases/Curved/king-iron-works-staircase-curved-led-artistic-panels.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-curved-modern-hor-bar-waterfront.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-curved-modern-rod-railing.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-curved-vine-leaf-panels.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-floating-honeycomb-laser-cut.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-15.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-16.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-17.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-18.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-19.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-20.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-21.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-213.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-214.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-23.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-24.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-273.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-305.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-470.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-471.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-486.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-512.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircase-website-514.jpg`,
      `${IMG}/Staircases/Curved/king-iron-works-staircases-modern-project-8.jpg`,
    ],  },
  { id: "curved-project-1", label: "Curved Project: Medallion Scrollwork", photos: [
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-425.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-426.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-427.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-428.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-429.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-430.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-431.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-432.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-433.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-434.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-435.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-436.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-437.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-438.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-439.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-440.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-441.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-442.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-443.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-444.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-445.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-446.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-447.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-448.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-449.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-450.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-451.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-452.jpg`,
      `${IMG}/Staircases/Curved/Project 1/king-iron-works-staircase-website-453.jpg`,
    ],  },
  { id: "curved-project-2", label: "Curved Project: Peacock Masterpiece", photos: [
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-chandelier-below.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-fleur-de-lis.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-grand-overhead.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-ornamental-completed.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-ornamental-gold-accents.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-ornamental-marble-foyer.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-ornamental-overhead.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-ornamental-spiral-above.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-peacock-above.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-peacock-chandelier.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-project1-hero.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-project1-reveal.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-curved-scrollwork-detail.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-1.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-104.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-105.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-12.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-308.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-315.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-316.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-327.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-328.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-329.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-330.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-332.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-334.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-335.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-339.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-341.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-342.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-350.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-351.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-352.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-353.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-354.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-355.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-356.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-361.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-362.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-363.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-364.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-365.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-366.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-367.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-368.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-456.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-457.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-458.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-459.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-460.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-462.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-463.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-464.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-465.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-466.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-5.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-536.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-538.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-540.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-541.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-542.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-7.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-93.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-94.jpg`,
      `${IMG}/Staircases/Curved/Project 2/king-iron-works-staircase-website-95.jpg`,
    ],  },
  { id: "floating-full", label: "Full Floating Staircases", photos: [
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-exterior-railing-project-145.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-exterior-railing-project-235.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-exterior-railing-project-281.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-exterior-railing-project-50.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-floating-rod-railing-led.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-144.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-145.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-149.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-241.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-242.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-270.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-278.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-279.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-402.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-403.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-404.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-405.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-406.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-407.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-408.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-409.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-410.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-411.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-412.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-413.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-414.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-415.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-416.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-417.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-418.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-419.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-420.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-421.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-422.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-423.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-424.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-461.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-511.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-513.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-516.jpg`,
      `${IMG}/Staircases/Floating/Full Floating/king-iron-works-staircase-website-517.jpg`,
    ],  },
  { id: "floating-mono-stringer", label: "Mono Stringer Staircases", photos: [
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-123.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-124.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-167.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-168.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-197.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-224.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-288.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-289.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-project-78.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-scroll-stone-colonial-2.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-exterior-railing-website-23.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-floating-cable-detail.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-floating-cantilever-dark.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-floating-glass-mono-stringer.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-floating-led-underlighting.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-floating-living-room.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-modern-cable-shiplap.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-modern-lifestyle-greenery.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-modern-multi-flight.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-modern-zigzag-stringer.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-switchback-horizontal-rod.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-10.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-109.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-11.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-113.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-114.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-115.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-118.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-119.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-125.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-126.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-127.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-128.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-129.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-130.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-136.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-137.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-138.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-139.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-140.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-141.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-142.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-143.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-147.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-150.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-151.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-152.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-153.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-154.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-155.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-156.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-157.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-173.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-174.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-190.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-191.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-192.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-193.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-2.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-212.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-215.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-216.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-217.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-218.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-219.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-220.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-222.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-244.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-245.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-246.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-247.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-248.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-249.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-25.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-27.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-271.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-275.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-282.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-285.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-290.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-291.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-292.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-293.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-301.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-302.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-303.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-304.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-306.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-307.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-309.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-31.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-310.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-311.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-318.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-319.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-32.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-320.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-321.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-322.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-323.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-33.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-34.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-35.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-36.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-37.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-38.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-39.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-4.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-40.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-41.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-500.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-504.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-51.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-518.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-519.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-520.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-521.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-522.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-523.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-524.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-525.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-526.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-527.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-528.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-529.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-533.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-537.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-539.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-6.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-60.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-61.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-62.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-63.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-64.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-65.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-8.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-9.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-96.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircase-website-97.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircases-floating-project-3.jpg`,
      `${IMG}/Staircases/Floating/Mono Stringer/king-iron-works-staircases-switchback-project-3.jpg`,
    ],  },
  { id: "floating-dual-stringer", label: "Dual Stringer Staircases", photos: [
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-154.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-159.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-160.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-161.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-177.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-181.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-182.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-227.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-276.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-280.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-exterior-railing-project-282.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-floating-industrial-plant-shelf.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-modern-glass-stainless.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-modern-two-story-arched.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-switchback-steel-oak.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-switchback-three-story.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-106.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-107.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-108.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-110.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-111.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-131.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-146.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-148.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-175.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-194.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-195.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-197.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-198.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-199.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-201.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-202.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-203.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-204.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-205.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-206.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-207.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-208.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-210.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-211.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-266.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-268.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-269.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-274.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-277.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-28.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-280.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-281.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-283.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-284.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-286.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-287.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-288.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-29.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-30.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-343.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-344.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-345.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-346.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-400.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-401.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-42.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-43.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-44.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-45.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-46.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-467.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-468.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-469.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-47.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-475.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-476.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-482.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-488.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-489.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-490.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-495.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-498.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-501.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-502.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-506.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-508.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-509.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-510.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircase-website-515.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircases-modern-project-1.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircases-modern-project-2.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircases-modern-project-3.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircases-modern-project-4.jpg`,
      `${IMG}/Staircases/Floating/Dual Stringer/king-iron-works-staircases-modern-project-5.jpg`,
    ],  },
  { id: "floating-exterior-staircases", label: "Floating Exterior Staircases", photos: [
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-porcelain-treads-twin-run.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-porcelain-sunlit-entry.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-porcelain-treads-head-on.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-porcelain-treads-entry-angle.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-frame-installed-landing.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-frame-stringer-profile.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-frame-entry-wide.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-frame-open-riser-underside.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-frame-landing-run-side.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-steel-frame-tread-pans.jpg`,
      `${IMG}/Staircases/Exterior-Entry/king-iron-works-staircase-exterior-steel-frame-angle.jpg`,
    ],  },
  { id: "spiral-interior", label: "Interior Spiral Staircases", photos: [
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-108.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-116.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-117.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-118.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-119.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-120.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-121.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-142.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-150.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-152.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-183.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-200.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-201.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-225.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-226.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-296.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-297.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-43.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-44.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-exterior-railing-project-45.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-black-steel-wood-treads.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-cable-hardwood.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-cable-railing-modern.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-interior-decorative-balusters.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-interior-wood-iron.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-modern-geometric.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-spiral-staircase-overhead-view.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-staircases-spiral-project-3.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-staircases-spiral-website-13.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-staircases-spiral-website-16.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-staircases-spiral-website-18.jpg`,
      `${IMG}/Staircases/Spiral/Interior Spiral/king-iron-works-staircases-spiral-website-7.jpg`,
    ],  },
  { id: "spiral-exterior", label: "Exterior Spiral Staircases", photos: [
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-155.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-17.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-178.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-179.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-180.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-219.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-220.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-221.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-38.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-39.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-40.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-exterior-railing-project-41.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-fence-5.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-spiral-staircase-exterior-residential-2.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-spiral-staircase-exterior-residential.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-spiral-staircase-fabrication-crane.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-spiral-staircase-stone-columns.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-curved-project-3.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-project-10.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-1.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-10.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-11.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-12.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-14.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-15.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-17.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-19.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-2.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-20.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-3.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-4.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-5.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-6.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-8.jpg`,
      `${IMG}/Staircases/Spiral/Exterior Spiral/king-iron-works-staircases-spiral-website-9.jpg`,
    ],  },
  { id: "grand-ornamental", label: "Grand Ornamental Staircases", photos: [
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-exterior-railing-project-184.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-exterior-railing-project-232.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-curved-scroll-circle-panels-1.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-curved-scroll-circle-panels-2.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-curved-scroll-circle-panels-3.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-grand-medallion-construction.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-grand-project2-hero.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-grand-project2-install.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-472.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-473.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-474.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-477.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-478.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-479.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-480.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-481.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-483.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-484.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-485.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-487.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-491.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-492.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-493.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-494.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-496.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-497.jpg`,
      `${IMG}/Staircases/Grand-Ornamental/king-iron-works-staircase-website-499.jpg`,
    ],  },
  { id: "exterior-railings", label: "Exterior Railings", photos: [
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-10.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-11.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-12.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-13.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-14.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-15.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-16.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-17.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-18.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-19.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-20.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-21.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-22.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-23.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-4.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-5.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-6.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-7.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-8.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-9.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-cable-deck-modern-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-cable-granite-gray-house-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-circle-motif-concrete-gray-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-circle-motif-knuckle-white-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-circle-motif-knuckle-white-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-circle-motif-stone-porch-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-handrail-porch-colonial-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-handrail-porch-colonial-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-balcony-modern-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-concrete-craftsman-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-concrete-modern-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-concrete-white-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-curved-stone-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-deck-blue-house-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-deck-gray-modern-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-deck-modern-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-deck-twotone-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-modern-deck-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-gray-twotone-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-modern-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-modern-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-modern-4.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-modern-gray-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-steps-craftsman-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-hor-bar-stone-steps-modern-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-mixed-circle-hor-bar-porch-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-panel-balcony-craftsman-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-10.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-102.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-107.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-109.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-11.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-110.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-111.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-112.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-12.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-125.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-126.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-132.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-133.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-134.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-135.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-14.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-141.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-143.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-144.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-149.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-15.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-151.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-153.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-16.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-165.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-166.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-170.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-172.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-174.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-175.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-176.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-192.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-195.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-196.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-202.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-203.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-204.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-205.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-21.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-216.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-217.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-218.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-22.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-223.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-23.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-24.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-241.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-249.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-250.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-251.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-252.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-253.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-259.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-260.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-262.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-263.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-264.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-265.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-266.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-267.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-268.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-273.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-274.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-275.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-28.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-285.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-287.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-290.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-291.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-292.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-293.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-294.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-30.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-31.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-32.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-33.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-34.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-35.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-36.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-37.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-48.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-49.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-5.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-51.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-52.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-57.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-6.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-63.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-67.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-68.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-69.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-7.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-8.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-83.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-84.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-85.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-86.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-87.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-88.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-89.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-9.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-90.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-project-91.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-brick-steps-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-colonial-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-colonial-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-colonial-detail-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-white-colonial-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-white-colonial-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-granite-white-colonial-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-stone-colonial-white-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-stone-detail-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-scroll-stone-steps-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-brick-steps-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-concrete-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-concrete-gray-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-deck-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-deck-forest-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-knuckle-stone-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-knuckle-stone-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-porch-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-porch-colonial-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-stone-5.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-stone-7.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-stone-patio-gray-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-vert-picket-walkway-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-1.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-10.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-11.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-12.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-13.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-14.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-15.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-16.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-17.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-18.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-19.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-2.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-20.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-21.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-22.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-26.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-27.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-28.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-29.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-3.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-30.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-31.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-32.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-33.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-34.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-35.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-4.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-5.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-6.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-7.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-8.jpg`,
      `${IMG}/Railings/Exterior-Railing/king-iron-works-exterior-railing-website-9.jpg`,
    ],  },
  { id: "interior-railings", label: "Interior Railings", photos: [
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-1.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-10.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-12.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-14.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-15.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-16.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-17.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-18.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-19.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-2.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-20.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-21.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-22.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-23.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-24.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-25.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-26.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-27.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-28.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-29.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-30.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-31.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-32.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-4.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-5.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-6.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-7.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-8.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-9.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-glass-panel-staircase-1.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-grid-pattern.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-modern-pendant-lights.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-panel-mesh-staircase-1.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-project-2.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-vert-picket-staircase-1.jpg`,
      `${IMG}/Railings/Interior-Railing/king-iron-works-interior-railing-wood-horizontal-bar.jpg`,
    ],  },
  { id: "cable-railings", label: "Cable Railings", photos: [
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-cedar-deck-stairs.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-hillside-outdoor.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-1.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-2.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-3.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-4.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-5.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-project-8.jpg`,
      `${IMG}/Railings/Cable-Railing/king-iron-works-cable-railing-website-1.jpg`,
    ],  },
  { id: "deck-railings", label: "Deck Railings", photos: [
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-1.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-privacy-screen-patio.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-1.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-2.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-3.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-4.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-5.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-6.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-project-9.jpg`,
      `${IMG}/Railings/Deck-Railing/king-iron-works-deck-railing-upper-craftsman.jpg`,
    ],  },
  { id: "commercial-railings", label: "Commercial Railings", photos: [
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-1.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-10.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-11.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-12.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-13.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-14.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-15.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-16.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-17.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-18.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-19.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-2.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-20.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-21.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-22.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-23.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-24.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-25.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-26.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-27.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-28.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-29.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-3.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-30.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-31.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-4.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-5.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-7.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-8.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-9.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-ada-ramp-stainless-1.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-ada-ramp-stainless-2.jpg`,
      `${IMG}/Railings/Commercial-Railing/king-iron-works-commercial-railing-industrial-concrete-1.jpg`,
    ],  },
  { id: "small-railings", label: "Small Railings", photos: [
      `${IMG}/Railings/Small-Railing/king-iron-works-small-railing-1.jpg`,
      `${IMG}/Railings/Small-Railing/king-iron-works-small-railing-2.jpg`,
      `${IMG}/Railings/Small-Railing/king-iron-works-small-railing-3.jpg`,
      `${IMG}/Railings/Small-Railing/king-iron-works-small-railing-4.jpg`,
    ],  },
  { id: "gates", label: "Gates", photos: [
      `${IMG}/Gates/king-iron-works-gate-10.jpg`,
      `${IMG}/Gates/king-iron-works-gate-11.jpg`,
      `${IMG}/Gates/king-iron-works-gate-12.jpg`,
      `${IMG}/Gates/king-iron-works-gate-13.jpg`,
      `${IMG}/Gates/king-iron-works-gate-14.jpg`,
      `${IMG}/Gates/king-iron-works-gate-15.jpg`,
      `${IMG}/Gates/king-iron-works-gate-16.jpg`,
      `${IMG}/Gates/king-iron-works-gate-17.jpg`,
      `${IMG}/Gates/king-iron-works-gate-18.jpg`,
      `${IMG}/Gates/king-iron-works-gate-19.jpg`,
      `${IMG}/Gates/king-iron-works-gate-2.jpg`,
      `${IMG}/Gates/king-iron-works-gate-20.jpg`,
      `${IMG}/Gates/king-iron-works-gate-21.jpg`,
      `${IMG}/Gates/king-iron-works-gate-22.jpg`,
      `${IMG}/Gates/king-iron-works-gate-23.jpg`,
      `${IMG}/Gates/king-iron-works-gate-24.jpg`,
      `${IMG}/Gates/king-iron-works-gate-25.jpg`,
      `${IMG}/Gates/king-iron-works-gate-26.jpg`,
      `${IMG}/Gates/king-iron-works-gate-27.jpg`,
      `${IMG}/Gates/king-iron-works-gate-28.jpg`,
      `${IMG}/Gates/king-iron-works-gate-3.jpg`,
      `${IMG}/Gates/king-iron-works-gate-31.jpg`,
      `${IMG}/Gates/king-iron-works-gate-4.jpg`,
      `${IMG}/Gates/king-iron-works-gate-5.jpg`,
      `${IMG}/Gates/king-iron-works-gate-6.jpg`,
      `${IMG}/Gates/king-iron-works-gate-7.jpg`,
      `${IMG}/Gates/king-iron-works-gate-8.jpg`,
      `${IMG}/Gates/king-iron-works-gate-9.jpg`,
      `${IMG}/Gates/king-iron-works-gate-circle-motif-driveway-1.jpg`,
      `${IMG}/Gates/king-iron-works-gate-circle-scroll-driveway-1.jpg`,
      `${IMG}/Gates/king-iron-works-gate-circle-scroll-driveway-2.jpg`,
      `${IMG}/Gates/king-iron-works-gate-custom-iron-webp.webp`,
      `${IMG}/Gates/king-iron-works-gate-garden-scrollwork-lantern.jpg`,
      `${IMG}/Gates/king-iron-works-gate-ornamental-black-gold-scrollwork.jpg`,
      `${IMG}/Gates/king-iron-works-gate-patio-scroll-bronze.jpg`,
      `${IMG}/Gates/king-iron-works-gate-scroll-driveway-1.jpg`,
      `${IMG}/Gates/king-iron-works-gate-scroll-residential-84.jpg`,
      `${IMG}/Gates/king-iron-works-gate-vert-picket-driveway-1.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-1.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-12.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-2.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-3.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-4.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-5.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-6.jpg`,
      `${IMG}/Gates/king-iron-works-gates-project-7.jpg`,
    ],  },
  { id: "fire-escapes", label: "Fire Escapes", photos: [
      `${IMG}/Fire-Escape/fire_escape_magazine_16x9.jpg`,
      `${IMG}/Fire-Escape/fire_escape_magazine_2x3.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-10.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-11.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-12.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-13.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-14.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-15.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-16.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-17.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-18.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-19.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-2.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-20.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-21.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-23.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-24.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-25.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-3.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-4.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-5.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-6.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-7.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-8.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-9.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-brick-building-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-brick-residential-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-brick-zigzag-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-commercial-below-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-commercial-stairs-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-installation-webp.webp`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-project-2.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-project-3.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-project-4.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-project-6.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-project-9.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-website-1.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-website-LIIMwNaI.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-website-PmBUKqXw.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-website-VrmKyMuo.jpg`,
      `${IMG}/Fire-Escape/king-iron-works-fire-escape-website-YgqFSong.jpg`,
    ],  },
  { id: "balconies", label: "Balconies", photos: [
      `${IMG}/Balcony/king-iron-works-balcony-1.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-10.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-11.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-12.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-13.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-2.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-3.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-4.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-5.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-6.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-7.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-8.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-9.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-ornamental-boston-brick.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-project-1.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-project-2.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-project-3.jpg`,
      `${IMG}/Balcony/king-iron-works-balcony-website-1.jpg`,
    ],  },
  { id: "juliet-balconies", label: "Juliet Balconies", photos: [
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-1.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-10.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-11.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-12.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-13.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-14.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-15.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-16.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-17.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-18.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-2.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-3.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-4.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-5.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-6.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-7.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-8.jpg`,
      `${IMG}/Juliet-Balcony/king-iron-works-juliet-balcony-9.jpg`,
    ],  },
  { id: "fences", label: "Fences", photos: [
      `${IMG}/Fence/king-iron-works-fence-1.jpg`,
      `${IMG}/Fence/king-iron-works-fence-10.jpg`,
      `${IMG}/Fence/king-iron-works-fence-11.jpg`,
      `${IMG}/Fence/king-iron-works-fence-12.jpg`,
      `${IMG}/Fence/king-iron-works-fence-13.jpg`,
      `${IMG}/Fence/king-iron-works-fence-14.jpg`,
      `${IMG}/Fence/king-iron-works-fence-15.jpg`,
      `${IMG}/Fence/king-iron-works-fence-16.jpg`,
      `${IMG}/Fence/king-iron-works-fence-17.jpg`,
      `${IMG}/Fence/king-iron-works-fence-18.jpg`,
      `${IMG}/Fence/king-iron-works-fence-2.jpg`,
      `${IMG}/Fence/king-iron-works-fence-3.jpg`,
      `${IMG}/Fence/king-iron-works-fence-4.jpg`,
      `${IMG}/Fence/king-iron-works-fence-5.jpg`,
      `${IMG}/Fence/king-iron-works-fence-6.jpg`,
      `${IMG}/Fence/king-iron-works-fence-7.jpg`,
      `${IMG}/Fence/king-iron-works-fence-8.jpg`,
      `${IMG}/Fence/king-iron-works-fence-9.jpg`,
      `${IMG}/Fence/king-iron-works-fence-knuckle-porch-1.jpg`,
      `${IMG}/Fence/king-iron-works-fence-vert-picket-driveway-1.jpg`,
      `${IMG}/Fence/king-iron-works-fence-vert-picket-yard-3.jpg`,
    ],  },
  { id: "structural-steel", label: "Structural Steel", photos: [
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-10.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-11.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-12.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-13.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-14.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-15.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-16.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-17.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-18.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-19.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-2.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-20.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-21.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-22.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-24.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-25.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-26.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-27.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-28.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-29.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-3.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-31.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-32.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-33.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-34.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-35.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-36.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-37.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-4.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-5.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-6.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-7.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-8.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-9.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-website-1.jpg`,
      `${IMG}/Structural-Steel/king-iron-works-structural-steel-website-2.jpg`,
    ],  },
  { id: "window-wells", label: "Window Wells", photos: [
      `${IMG}/Window-Well/king-iron-works-window-well-1.jpg`,
      `${IMG}/Window-Well/king-iron-works-window-well-horizontal-bar-modern.jpg`,
      `${IMG}/Window-Well/king-iron-works-window-well-project-1.jpg`,
      `${IMG}/Window-Well/king-iron-works-window-well-website-1.jpg`,
      `${IMG}/Window-Well/king-iron-works-window-well-website-2.jpg`,
      `${IMG}/Window-Well/king-iron-works-window-well-website-3.jpg`,
    ],  },
  { id: "window-guards", label: "Window Guards", photos: [
      `${IMG}/Window-Guard/king-iron-works-window-guard-website-1.jpg`,
      `${IMG}/Window-Guard/king-iron-works-window-guard-website-2.jpg`,
      `${IMG}/Window-Guard/king-iron-works-window-guard-website-3.jpg`,
    ],  },
  { id: "ada-ramps", label: "ADA Ramps", photos: [
      `${IMG}/ada-ramp/king-iron-works-ada-ramp-1.jpg`,
      `${IMG}/ada-ramp/king-iron-works-ada-ramp-2.jpg`,
      `${IMG}/ada-ramp/king-iron-works-ada-ramp-3.jpg`,
    ],  },
  { id: "shop-process", label: "Shop & Process", photos: [
      `${IMG}/Shop-Process/king-iron-works-install-welding-onsite.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-branded-truck.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-butterfly-metal-art.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-curved-frame-fabrication.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-curved-frame-wood-jig.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-curved-stringer-install.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-interior-webp.webp`,
      `${IMG}/Shop-Process/king-iron-works-shop-kayky-guitar-gate-art.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-kayky-staircase.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-10.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-11.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-12.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-13.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-2.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-3.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-4.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-6.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-7.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-8.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-project-9.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-1.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-2.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-3.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-4.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-5.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-6.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-process-website-7.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-welding-sparks.jpg`,
      `${IMG}/Shop-Process/king-iron-works-shop-workbench-banner.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-floating-window-wall.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-100.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-101.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-102.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-120.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-132.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-133.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-134.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-135.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-14.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-158.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-159.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-160.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-161.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-162.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-163.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-164.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-166.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-171.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-172.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-176.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-177.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-178.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-179.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-180.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-181.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-182.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-183.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-184.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-185.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-186.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-187.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-188.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-189.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-196.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-209.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-221.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-223.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-224.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-225.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-226.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-227.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-228.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-229.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-230.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-231.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-232.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-233.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-238.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-239.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-240.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-243.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-250.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-251.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-252.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-253.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-254.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-255.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-256.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-257.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-258.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-259.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-260.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-261.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-262.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-263.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-264.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-265.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-296.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-297.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-298.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-299.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-300.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-312.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-313.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-314.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-331.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-333.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-336.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-337.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-338.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-340.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-357.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-358.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-359.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-360.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-369.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-370.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-371.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-372.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-373.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-374.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-375.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-376.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-377.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-378.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-379.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-380.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-381.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-382.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-383.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-384.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-385.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-386.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-387.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-388.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-389.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-390.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-391.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-392.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-393.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-394.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-395.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-396.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-397.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-398.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-399.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-455.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-530.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-531.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-532.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-535.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-55.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-56.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-57.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-58.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-59.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-91.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-92.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-98.jpg`,
      `${IMG}/Shop-Process/king-iron-works-staircase-website-99.jpg`,
    ],  },
];
export const allPhotos = categories.flatMap((c) => c.photos.map((src) => ({ src, category: c.id })));
export function getCategoryLabel(id: string): string { return categories.find((c) => c.id === id)?.label ?? id; }
