// Plain-language explanation for every measurement field, shown behind the
// "i" next to its label.
//
// The person holding the tape is often not the person who designed the sheet.
// Each entry answers one question — WHERE do I put the tape, and what counts —
// in the words a measurer would use, not the words the data model uses.
//
// Keyed by the same i18n key as the field's label, so a field opts in with
// help="<key>" and nothing else.

type HelpDict = Record<string, string>;

const en: HelpDict = {
  alongPlatform: "Distance along the platform from its start to this post.",
  anchorInto: "What the anchor actually goes into — granite, concrete, wood, steel.",
  balAnchorType: "What you intend to use — wedge, epoxy, through-bolt.",
  balCorners: "Any corners in the run and what angle they turn.",
  balDoorOpening: "For a juliet, the width of the door opening it closes off.",
  balDrainage: "Scuppers, drains or a slope the rail and its base plates have to clear.",
  balEdgeCondition: "State of the slab edge — spalling, a drip groove, an overhang, exposed rebar.",
  balEdgeDistance: "Centre of the anchor to the edge of the slab. Too close and the edge blows out when you tighten it.",
  balEdgeLength: "The full length of edge getting a rail, end to end.",
  balEmbedment: "How deep the anchor goes into the slab. This plus any cover underneath has to fit inside the slab thickness, or it breaks through the bottom.",
  balFinishedFloor: "What the floor will be when the rail actually goes on. Say if a topping is still to come — it changes the post height.",
  balGuardHeight: "From the FINISHED floor to the top of the rail. If tile or decking is going down later, measure from where the floor will end up, not where it is now.",
  balKind: "A full balcony you stand on, or a juliet that just closes a door opening.",
  balMinCover: "How much solid slab you want left below the anchor. Leave blank if none is specified.",
  balMount: "Where the posts land — on top of the slab, on its edge, core drilled, or embedded.",
  balPicketSpacing: "Clear gap between pickets. Over 4 inches will be flagged.",
  balPlatePlan: "Base plate size and the bolt pattern on it.",
  balProjection: "How far the balcony sticks out from the building.",
  balReturns: "How the rail finishes at each end — into the wall, a return, a free end.",
  balSlabMaterial: "Concrete, steel deck, wood framing. Decides what anchor works at all.",
  balSlabThickness: "How thick the slab is at the edge. The anchor has to fit inside this — get it from a drawing or a drilled test hole, not a guess.",
  bottomAdjustment: "How much the bottom floor will move. Plus if it comes up, minus if it goes down.",
  brackets: "How many wall brackets and how far apart.",
  clearWidth: "Clear walking width from the column to the outside rail.",
  clipDetail: "How the clip attaches and what it lands on.",
  color: "Finish colour. Say if it has to match something already on site.",
  columnDLbl: "Depth of that column at the same height.",
  columnSize: "Diameter of the centre column.",
  columnToPlatformEdge: "Clear distance from the column face to the edge of the platform.",
  columnToWall: "Clear distance from the face of the existing column to the wall.",
  columnWLbl: "Width of the existing column at the height where the rail attaches — not at the base, which is often wider.",
  connAttachTo: "What this end of the rail lands on — a new post, a wall, an existing column, the floor, another span, or nothing.",
  connMaterial: "What that thing is made of. Decides whether welding is even possible.",
  connMethod: "How it fixes to that. The list changes to only what is valid for what you picked.",
  curveArc: "Length measured along the curve itself. Checked against the radius and chord.",
  curveChord: "Straight line from one end of the curve to the other.",
  curveRadius: "Radius to the centreline of the rail.",
  curveRise: "Total rise across the curve. Leave blank for a level radius rail.",
  curveSweep: "Total number of degrees the curve turns through.",
  depth: "Depth of the landing, front to back.",
  diameter: "Overall diameter of the spiral, outside to outside.",
  distanceFromFirst: "From the edge of the first tread to the edge of the tread this post sits on.",
  existingMaterial: "What the existing post is made of. Only steel can be welded to.",
  existingPostDepth: "Depth of that existing post.",
  existingPostWidth: "Face width of the existing post you are attaching to.",
  extensions: "Code extensions past the top and bottom risers, where they are required.",
  fenceEndTerm: "What it finishes against.",
  fenceFooting: "Depth of the post footings. Below frost line.",
  fenceGates: "How many gates go in this run and roughly where.",
  fenceHeight: "Height of the fence itself, ground to the top of the panel.",
  fencePanelWidth: "The nominal width of one panel or bay, if you are using a standard panel.",
  fencePicketSpacing: "Clear gap between pickets. Over 4 inches will be flagged.",
  fencePostSize: "Section size of the posts.",
  fencePostSpacing: "Centre to centre between posts.",
  fenceSegFollows: "Racking tilts each panel to follow the slope. Stepping keeps panels level and steps them down. Changes the whole panel order.",
  fenceSegGrade: "How much the ground rises or falls along this stretch.",
  fenceSegHeight: "Height along this stretch, if it differs from the run.",
  fenceSegLength: "Length of THIS straight stretch only, corner to corner.",
  fenceSegObstruction: "Trees, rock, a slab, anything on the line here.",
  fenceSegPanels: "How many panels fit in this stretch.",
  fenceSegTurn: "How many degrees the fence turns at the END of this stretch. Leave blank if it carries straight on.",
  fenceStartTerm: "What the run starts against — a house corner, an existing fence, a free-standing post.",
  fenceTotalRun: "Tape the whole run end to end, in one go, independent of the segments. The sheet checks the segments add up to this.",
  fenceUtilities: "What is buried on the line. Get it marked before anyone digs a footing.",
  finish: "Coating system. Default is standard DTM paint unless galvanizing or powder coat was asked for.",
  fireAccess: "How the crew gets to it. Alley width, whether staging or a lift fits, permits for the sidewalk.",
  fireAnchorCondition: "The connection to the building — the thing that actually fails. Weeping rust, cracked mortar, movement.",
  fireAnchorCount: "How many anchors hold this level.",
  fireAnchorSpacing: "Centre to centre between anchors.",
  fireAnchorType: "How it ties to the building — through-bolt, expansion anchor, embedded. Say what you can actually see.",
  fireCondNotes: "Anything else that matters for this level.",
  fireCracks: "Cracked welds, split stringers, broken castings — where, and how long.",
  fireDeck: "What you walk on — bar grating, checker plate, open bar. Note if it is worn through anywhere.",
  fireDeckCondition: "State of the grating or treads. Holes, missing bar, anything soft underfoot.",
  fireDeployed: "With the ladder down, how far is the bottom rung still above the ground. It should be zero — anything left is how far someone has to drop.",
  fireFloorToFloor: "From this balcony's deck down to the deck of the level below. The stair's risers have to add up to this.",
  fireGuardCondition: "Loose or missing pickets, rail that moves when you push it.",
  fireGuardHeight: "Deck to the top of the guard rail. 42 inches is the current minimum for new work; older escapes are often less, which is what you are recording.",
  fireHeightGrade: "From this balcony's deck straight down to the ground.",
  fireLadderLength: "Overall length of the ladder itself.",
  fireLadderOperates: "Try it. Does it actually come down — freely, stiffly, or not at all?",
  fireLadderRung: "Centre to centre between rungs.",
  fireLadderType: "Drop, swing, counterbalance or fixed. If it is fixed it never moves; the others are supposed to.",
  fireLadderWidth: "Outside to outside of the rails.",
  fireLandingSurface: "What it comes down onto — sidewalk, grass, alley, a roof.",
  fireLoadTest: "What the load test showed, or why it was not done.",
  fireObstructions: "What is in the way underneath. Condenser units, fences, parked cars, planting.",
  fireOpening: "Whether this balcony serves a window or a door.",
  fireOpeningW: "Width of the window or door this balcony serves.",
  firePaintSystem: "The existing coating and what state it is in.",
  firePicketSpacing: "Clear gap between pickets. Over 4 inches will be flagged.",
  firePlatLength: "The balcony along the building wall, end to end.",
  firePlatWidth: "How far the balcony sticks out from the wall.",
  fireRating: "Your verdict for this level: pass, monitor, or fail.",
  fireRust: "Where the rust is and how deep. Surface scale and structural loss are different problems.",
  fireSectionLoss: "At the worst spot, how much steel is actually gone. Measure it if you can get a caliper on it.",
  fireSillToPlatform: "From the balcony deck up to the sill you climb over. A high sill is a violation on its own.",
  fireStairAngle: "Pitch off horizontal. Checked against the rise and run you just recorded.",
  fireStairRise: "Height of one riser. Risers times this has to equal the floor-to-floor above.",
  fireStairRisers: "Count the risers, not the treads. There is always one more riser than tread.",
  fireStairRun: "Depth of one tread, front to back.",
  fireStairWidth: "Clear width between the stringers.",
  fireStories: "How many floors this fire escape serves.",
  fireStowed: "With the ladder up and stowed, how far is the bottom rung above the ground.",
  fireTotalHeight: "From the deck of the TOP balcony straight down to the ground. Cross-checked against the floor-to-floor heights you record per level.",
  fireViolations: "Copy what the notice actually cites, in its words. That is what has to be signed off.",
  fireWallMaterial: "What the anchors go into — brick, block, concrete, stone or wood frame. Soft old mortar changes what will hold.",
  flightCtrlRise: "Total rise of THIS flight, measured on its own.",
  flightCtrlRun: "Total run of THIS flight, measured on its own.",
  flightRake: "Nose to nose along THIS flight only. Needed per flight when the stair turns, because one overall rake cannot verify flights going different directions.",
  floorChangeQuestion: "Will the floor height change before the railing goes in? New tile, stone or decking moves every post.",
  floorToFloor: "Finished floor to finished floor. If a floor finish is still to be laid, say so in Site & finish.",
  fromEdge: "Setback from the open edge of the tread to the post.",
  gateDiagA: "Corner to opposite corner of the opening. Both diagonals matching means the opening is square.",
  gateDiagB: "The other diagonal. Should match A.",
  gateDropRod: "On a double gate, the rod that pins the passive leaf to the ground.",
  gateFooting: "How deep the footing goes. Below frost line for a driveway gate.",
  gateGradeRise: "Walk the path the gate sweeps through. How much does the ground RISE from the closed position to fully open? Plus if it climbs, minus if it falls. This is the number that decides whether the gate binds.",
  gateGroundClearance: "With the gate closed, the gap under the bottom of the leaf.",
  gateHeightHinge: "Ground to the top of the post on the hinge side.",
  gateHeightLatch: "Ground to the top of the post on the latch side. Different from the hinge side tells you the grade across the opening.",
  gateHingeSide: "Standing outside looking at the gate, which side the hinges are on.",
  gateHinges: "Type and how many per leaf.",
  gateInfill: "What fills the leaf — pickets, panel, mesh.",
  gateLatch: "How it latches, and whether it locks.",
  gateOpener: "Make and model of the operator, if there is one.",
  gateOperation: "How it moves. Only swinging gates get the ground-clearance check.",
  gatePicketSpacing: "Clear gap between pickets. On a pool gate this is a hard fail over 4 inches.",
  gatePostMaterial: "Steel, wood, masonry pier. Changes how the hinges attach.",
  gatePostSize: "Section size of the posts, if they are new or you can measure the existing ones.",
  gatePower: "Is there power at the gate already, or does it have to be run?",
  gateSafety: "Loops, photo eyes, safety edges — what is fitted. An automated gate without them is a liability.",
  gateSurface: "What it swings over — asphalt, concrete, gravel, grass. Gravel moves and needs more clearance.",
  gateSwingDir: "Which way it opens. Note that a gate swinging uphill is the one that binds.",
  gateUse: "What the gate is for. A pool gate has stricter rules than a service gate.",
  gateWidthBottom: "Post to post at the BOTTOM. Rarely the same as the top — that difference is why a square leaf sometimes will not fit.",
  gateWidthTop: "Post to post at the TOP of the opening. Measure the clear gap, not post centres.",
  infillGap: "Measure from the end picket to the FACE of the trim at the bottom of the column — the surface that sticks out furthest. The sheet works out how big the gap becomes above the trim, where the column steps back.",
  landingDiag: "Corner to opposite corner of the landing. Proves it is actually square before you fabricate to right angles.",
  landingNote: "Anything about the landing the shop needs — obstructions, a step down, an odd shape.",
  length: "Length along the direction the rail runs.",
  matBottomRail: "Bottom rail section, if there is one.",
  matNotes: "Anything else the shop needs to order or know.",
  matPicketSpacing: "Clear gap between pickets. Over 4 inches will be flagged.",
  moldingHeightLbl: "How far up that molding runs.",
  moldingLbl: "Projection of any molding or skirt at the base of the column, beyond the column face.",
  mountType: "How the post fixes down — core-drilled into the tread, a base plate on top, or side-mounted to the stringer.",
  nominalRise: "What the drawing or the builder says the riser should be. The measured risers are checked against it.",
  nominalRun: "What the drawing says the tread should be.",
  nosing: "How far the tread overhangs the riser below it.",
  notes: "Anything that does not fit another box.",
  plumbLbl: "How far out of plumb the column is over its height. A leaning column changes every span around it.",
  pointType: "What is at this spot — a new railing post, an existing structural post, a concrete wall, or a clip.",
  postAnchors: "Anchor pattern — how many, what size.",
  postEdgeDist: "From the anchor to the nearest edge of the concrete or stone. Too close and it breaks out.",
  postPlate: "Base plate size and which way round it sits.",
  postRefLbl: "Whether your post dimensions are to the centre of the post or to its face. Get this wrong and every post moves by half a post.",
  postSetback: "Setback from the nosing back to the post.",
  postSubstrate: "Thickness and condition of what you are fixing into.",
  railHeight: "From the nosing line (or the floor on a level run) to the top of the rail.",
  railKind: "Guardrail stops a fall, handrail is what you hold. Say if this run needs both.",
  railSide: "Which side the rail goes on, standing at the bottom looking up.",
  rakeLength: "Straight line along the nosings, bottom nosing to top nosing. This is the rail line — the single most useful number on the sheet.",
  rampRunH: "Horizontal run of the ramp — not the sloped length.",
  rampSlopeLen: "Length measured along the ramp surface itself.",
  returnsLabel: "How the rail finishes — a return into the wall, a loop end, or open.",
  rise: "Height of this one riser — top of one tread to top of the next.",
  rotation: "Total degrees the spiral turns from bottom to top.",
  run: "Depth of this one tread, nose to riser. Measure at the walkline, not at the narrow end.",
  segmentRise: "Total rise across this segment.",
  segmentType: "What this piece of the run is — a flight of stairs, a landing, a ramp or a curve.",
  skirtHeight: "Height of the skirt or molding on the post.",
  spanName: "Name this rail piece so the shop can match it to the drawing.",
  stairAngle: "Pitch off horizontal. Put a digital level on the nosings. Checked against the rise and run you recorded.",
  stairSideLookingUp: "Which side, standing at the bottom of the stairs looking up. Always use that view so left and right never flip.",
  stepsThisFlight: "How many treads in this flight. Remember there is always one more riser than tread.",
  topAdjustment: "How much the top floor will move, same convention.",
  topSpanLbl: "Clear length of this piece at the top rail. This is the fabrication length.",
  totalRise: "Bottom finished floor to top finished floor, in one measurement. The individual risers have to add up to this.",
  totalRun: "Horizontal distance from the face of the bottom riser to the face of the top riser.",
  treadCovering: "What is going on the treads, if anything, and how thick.",
  bottomSurface: "What the bottom of the rail lands on TODAY — concrete, wood subfloor, soil. This decides the base plate and the anchor, so say what is actually there now, not what it will become.",
  topSurface: "What the top of the rail lands on today, same idea as the bottom. A rail bolted to a subfloor that later gets tile ends up short.",
  futureTopping: "Anything going ON TOP of that surface later — tile, stone, wood — and how thick. We add it to the post length now so the rail still sits right after the finisher has been.",
  orientationLbl: "Looking UP the stairs, which side has a wall against it. The walled side gets no railing, so this decides what we build. On a stair that turns, each flight is asked separately — after a 180° turn the same wall is on your other hand.",
  treadsCount: "How many treads in the spiral.",
  turn: "Which way the stair turns after this landing, if it turns at all.",
  typicalRise: "The riser height that most steps share. Fill this once, then use Copy to all and correct the odd ones.",
  typicalRun: "The tread depth most steps share. Fill once, copy, then correct the odd ones.",
  wallFinish: "What the wall finish will be where the rail attaches.",
  wellBandFrom: "Top edge of this surface, measured down from the top of the well wall. Optional.",
  wellBandLabel: "What this surface is — water table trim, lap siding, foundation. Anything the guard runs past.",
  wellBandSetback: "How far this surface sits BACK from the one that sticks out furthest. The furthest-out surface is 0.",
  wellBandTo: "Bottom edge of this surface, same reference. Optional.",
  wellConstruction: "What the well walls are made of. Poured concrete and block take anchors differently, and corrugated steel usually needs a frame rather than bolts.",
  wellDepth: "Top of the well wall straight down to the floor of the well. Over 44 inches and egress needs a ladder.",
  wellDiagA: "Corner to opposite corner inside the well. Take both diagonals — if they differ the well is out of square and a rectangular grate will not drop in.",
  wellDiagB: "The other inside diagonal. Should match diagonal A.",
  wellGateHinge: "Which side the hinges go on.",
  wellGateLatch: "How it latches. Egress hardware has to open from inside the well with no key and no special knowledge.",
  wellGateSwing: "Which way the gate opens. Egress gates should swing out of the well.",
  wellGateWidth: "Clear opening of the gate once it is open — not the frame size.",
  wellGrateBearing: "How the grate sits: laid on top of the wall, recessed into it, or dropped into an angle frame.",
  wellGrateInfill: "What the grate is made of and how tight the bars are — the gap between bars still has to stop the sphere.",
  wellGrateLoad: "What it has to carry. Say if it is walked on, or if snow load matters.",
  wellGuardHeight: "From the top of the well wall to the top of the guard rail.",
  wellInsideLength: "Clear opening along the house, wall face to wall face inside the well. This is the number a grate is cut to.",
  wellInsideProjection: "Clear opening from the foundation out to the inside face of the far wall.",
  wellLadderRungs: "How many rungs. Depth divided by rung spacing, near enough.",
  wellLadderSpacing: "Centre of one rung to centre of the next. 18 inches is the usual maximum.",
  wellLadderStandoff: "From the face of the rung back to the wall behind it — the room your boot needs. 3 inches minimum.",
  wellLadderTopExt: "How far the ladder rails run above the top of the well wall, to grab as you climb out.",
  wellLadderWidth: "Outside to outside of the ladder rails.",
  wellLengthAtHouse: "Along the house, outside face to outside face of the well walls. Measure at the top of the wall, where the grate or guard will land.",
  wellMaxSphere: "The sphere your inspector uses. Normally 4 inches: no gap anywhere may let a 4 inch ball pass.",
  wellPostToWall: "The gap you measured from the face of the post to the surface that sticks out furthest. The sheet works out whether that leaves too big a gap further back.",
  wellProjection: "Straight out from the house wall to the outside face of the far well wall, at the top.",
  wellSillToFloor: "From the window sill down to the floor of the well. Tells us where the top of a ladder has to land.",
  wellTopToGrade: "How far the top of the wall sits above the surrounding dirt. Write a minus number if the wall is below grade.",
  wellWallRef: "Name the surface that sticks out FURTHEST from the house — usually the trim board at the bottom of the siding. Every other surface is measured back from this one.",
  wellWallThickness: "How wide the top of the well wall is — the surface a grate or base plate actually sits on.",
  wellWindowH: "Height of the basement window, frame to frame.",
  wellWindowSwing: "Which way the window moves. A casement that swings out into the well steals space a ladder needs.",
  wellWindowW: "Width of the basement window itself, frame to frame.",
  width: "Clear width of the stair, inside face to inside face.",
  widthBottom: "Stair width measured at the bottom.",
  widthMid: "Stair width measured in the middle. Old stairs are rarely parallel.",
  widthTop: "Stair width measured at the top.",
  winderRunIn: "Tread depth at the narrow inside edge of a winder.",
  winderRunOut: "Tread depth at the wide outside edge of a winder.",
  winderTurn: "How many degrees this winder tread turns the direction of travel.",
};

const pt: HelpDict = {
  alongPlatform: "Distância ao longo do patamar, do início até este poste.",
  anchorInto: "No que o chumbador realmente entra — granito, concreto, madeira, aço.",
  balAnchorType: "O que você pretende usar — cunha, epóxi, parafuso passante.",
  balCorners: "Cantos no percurso e com que ângulo viram.",
  balDoorOpening: "Na julieta, a largura do vão da porta que ela fecha.",
  balDrainage: "Escoadores, ralos ou caimento que o guarda-corpo e as placas de base precisam evitar.",
  balEdgeCondition: "Estado da borda da laje — desplacamento, pingadeira, balanço, ferragem exposta.",
  balEdgeDistance: "Do centro do chumbador até a borda da laje. Perto demais e a borda estoura ao apertar.",
  balEdgeLength: "O comprimento total da borda que vai receber guarda-corpo, de ponta a ponta.",
  balEmbedment: "Quanto o chumbador entra na laje. Isso mais o cobrimento embaixo tem que caber na espessura da laje, ou ele rompe o fundo.",
  balFinishedFloor: "Qual será o piso quando o guarda-corpo for instalado. Diga se ainda falta contrapiso — isso muda a altura do poste.",
  balGuardHeight: "Do piso ACABADO ao topo do guarda-corpo. Se ainda vai entrar piso ou deck, meça de onde o piso vai ficar, não de onde está agora.",
  balKind: "Sacada de pisar, ou julieta que só fecha o vão da porta.",
  balMinCover: "Quanto de laje maciça você quer deixar abaixo do chumbador. Deixe vazio se não houver especificação.",
  balMount: "Onde os postes apoiam — em cima da laje, na borda dela, furo com copo, ou embutido.",
  balPicketSpacing: "Vão livre entre balaústres. Acima de 4 polegadas será sinalizado.",
  balPlatePlan: "Dimensão da placa de base e a furação nela.",
  balProjection: "O quanto a sacada avança a partir do prédio.",
  balReturns: "Como o guarda-corpo termina em cada ponta — na parede, com retorno, ou ponta livre.",
  balSlabMaterial: "Concreto, laje de aço, estrutura de madeira. Define qual chumbador funciona.",
  balSlabThickness: "Espessura da laje na borda. O chumbador tem que caber dentro disso — pegue de projeto ou de um furo de teste, não chute.",
  bottomAdjustment: "Quanto o piso de baixo vai mudar. Positivo se subir, negativo se descer.",
  brackets: "Quantos suportes de parede e a que distância.",
  clearWidth: "Largura livre de caminhamento, da coluna até o corrimão externo.",
  clipDetail: "Como o clip prende e em que apoia.",
  color: "Cor do acabamento. Diga se precisa combinar com algo que já está no local.",
  columnDLbl: "Profundidade dessa coluna na mesma altura.",
  columnSize: "Diâmetro da coluna central.",
  columnToPlatformEdge: "Distância livre da face da coluna até a borda do patamar.",
  columnToWall: "Distância livre da face da coluna existente até a parede.",
  columnWLbl: "Largura da coluna existente na altura onde o corrimão prende — não na base, que costuma ser mais larga.",
  connAttachTo: "Onde esta ponta do corrimão apoia — poste novo, parede, coluna existente, piso, outro vão, ou nada.",
  connMaterial: "Do que aquilo é feito. Define se dá para soldar.",
  connMethod: "Como fixa nisso. A lista muda para mostrar só o que é válido para o que você escolheu.",
  curveArc: "Comprimento medido pela própria curva. Conferido contra raio e corda.",
  curveChord: "Linha reta de uma ponta da curva à outra.",
  curveRadius: "Raio até o eixo do corrimão.",
  curveRise: "Altura total ao longo da curva. Deixe vazio em curva plana.",
  curveSweep: "Total de graus que a curva descreve.",
  depth: "Profundidade do patamar, da frente ao fundo.",
  diameter: "Diâmetro total da caracol, de fora a fora.",
  distanceFromFirst: "Da borda do primeiro piso até a borda do piso onde este poste fica.",
  existingMaterial: "Do que é o poste existente. Só aço aceita solda.",
  existingPostDepth: "Profundidade desse poste existente.",
  existingPostWidth: "Largura da face do poste existente em que você vai fixar.",
  extensions: "Prolongamentos de norma além do primeiro e do último espelho, onde forem exigidos.",
  fenceEndTerm: "Onde ele termina.",
  fenceFooting: "Profundidade das sapatas dos postes. Abaixo da linha de gelo.",
  fenceGates: "Quantos portões entram neste trecho e mais ou menos onde.",
  fenceHeight: "Altura da própria cerca, do solo ao topo do painel.",
  fencePanelWidth: "Largura nominal de um painel ou vão, se estiver usando painel padrão.",
  fencePicketSpacing: "Vão livre entre balaústres. Acima de 4 polegadas será sinalizado.",
  fencePostSize: "Dimensão do perfil dos postes.",
  fencePostSpacing: "De centro a centro entre postes.",
  fenceSegFollows: "Inclinar gira cada painel para acompanhar o declive. Degrau mantém os painéis no nível e vai descendo em degraus. Muda toda a produção dos painéis.",
  fenceSegGrade: "Quanto o solo sobe ou desce ao longo deste trecho.",
  fenceSegHeight: "Altura neste trecho, se for diferente do resto.",
  fenceSegLength: "Comprimento SÓ deste trecho reto, de canto a canto.",
  fenceSegObstruction: "Árvores, rocha, laje, qualquer coisa na linha aqui.",
  fenceSegPanels: "Quantos painéis cabem neste trecho.",
  fenceSegTurn: "Quantos graus a cerca vira no FIM deste trecho. Deixe vazio se seguir reto.",
  fenceStartTerm: "Onde o trecho começa — canto da casa, cerca existente, poste isolado.",
  fenceTotalRun: "Meça o trecho inteiro de ponta a ponta, de uma vez, sem depender dos segmentos. A ficha confere se os segmentos somam isso.",
  fenceUtilities: "O que está enterrado na linha. Peça a marcação antes de alguém cavar sapata.",
  finish: "Sistema de pintura. O padrão é tinta DTM comum, salvo se pediram galvanização ou pintura eletrostática.",
  fireAccess: "Como a equipe chega. Largura da viela, se cabe andaime ou plataforma, licença para a calçada.",
  fireAnchorCondition: "A ligação com o prédio — o que de fato falha. Ferrugem escorrendo, argamassa trincada, movimento.",
  fireAnchorCount: "Quantos chumbadores seguram este nível.",
  fireAnchorSpacing: "De centro a centro entre chumbadores.",
  fireAnchorType: "Como prende no prédio — parafuso passante, chumbador de expansão, embutido. Diga o que dá para ver de fato.",
  fireCondNotes: "Qualquer outra coisa que importe neste nível.",
  fireCracks: "Solda trincada, longarina rachada, peça fundida quebrada — onde e de que tamanho.",
  fireDeck: "O que se pisa — grade, chapa xadrez, barra. Anote se estiver furado em algum ponto.",
  fireDeckCondition: "Estado da grade ou dos degraus. Furos, barra faltando, qualquer ponto mole ao pisar.",
  fireDeployed: "Com a escada estendida, quanto o degrau mais baixo ainda fica acima do solo. Deveria ser zero — o que sobrar é o tanto que alguém teria que pular.",
  fireFloorToFloor: "Do piso desta sacada até o piso do nível abaixo. Os espelhos da escada precisam somar exatamente isto.",
  fireGuardCondition: "Balaústres soltos ou faltando, guarda-corpo que mexe quando você empurra.",
  fireGuardHeight: "Do piso ao topo do guarda-corpo. 42 polegadas é o mínimo atual para obra nova; escadas antigas costumam ter menos, e é isso que você está registrando.",
  fireHeightGrade: "Do piso desta sacada reto até o solo.",
  fireLadderLength: "Comprimento total da própria escada.",
  fireLadderOperates: "Teste. Ela desce mesmo — livre, dura, ou nem desce?",
  fireLadderRung: "De centro a centro entre degraus.",
  fireLadderType: "Deslizante, basculante, com contrapeso ou fixa. Fixa nunca se move; as outras deveriam se mover.",
  fireLadderWidth: "De fora a fora dos montantes.",
  fireLandingSurface: "Onde ela chega — calçada, grama, viela, um telhado.",
  fireLoadTest: "O que o teste de carga mostrou, ou por que não foi feito.",
  fireObstructions: "O que está no caminho embaixo. Condensadores, cercas, carros estacionados, plantas.",
  fireOpening: "Se esta sacada atende uma janela ou uma porta.",
  fireOpeningW: "Largura da janela ou porta que esta sacada atende.",
  firePaintSystem: "O revestimento existente e em que estado está.",
  firePicketSpacing: "Vão livre entre balaústres. Acima de 4 polegadas será sinalizado.",
  firePlatLength: "A sacada junto à parede do prédio, de ponta a ponta.",
  firePlatWidth: "O quanto a sacada avança a partir da parede.",
  fireRating: "Seu veredito para este nível: aprovado, monitorar ou reprovado.",
  fireRust: "Onde está a ferrugem e quão profunda. Casca superficial e perda estrutural são problemas diferentes.",
  fireSectionLoss: "No pior ponto, quanto de aço já se foi. Meça com paquímetro se conseguir alcançar.",
  fireSillToPlatform: "Do piso da sacada até o peitoril que se transpõe. Peitoril alto já é uma violação por si só.",
  fireStairAngle: "Inclinação em relação à horizontal. Conferida contra o espelho e o piso que você acabou de anotar.",
  fireStairRise: "Altura de um espelho. Espelhos vezes esta medida tem que dar o piso a piso acima.",
  fireStairRisers: "Conte os espelhos, não os pisos. Sempre há um espelho a mais que pisos.",
  fireStairRun: "Profundidade de um piso, da frente ao fundo.",
  fireStairWidth: "Largura livre entre as longarinas.",
  fireStories: "Quantos pavimentos esta escada de incêndio atende.",
  fireStowed: "Com a escada recolhida, a que altura do solo fica o degrau mais baixo.",
  fireTotalHeight: "Do piso da sacada MAIS ALTA reto até o solo. É conferido contra as alturas piso a piso que você anota em cada nível.",
  fireViolations: "Copie o que a notificação realmente cita, com as palavras dela. É isso que precisa ser liberado.",
  fireWallMaterial: "Onde os chumbadores entram — tijolo, bloco, concreto, pedra ou madeira. Argamassa velha e mole muda o que vai segurar.",
  flightCtrlRise: "Altura total SÓ deste lance, medida sozinha.",
  flightCtrlRun: "Avanço total SÓ deste lance, medido sozinho.",
  flightRake: "De bico a bico SÓ deste lance. Necessário por lance quando a escada vira, porque um rake geral não verifica lances em direções diferentes.",
  floorChangeQuestion: "O piso vai mudar de altura antes do guarda-corpo entrar? Piso novo, pedra ou deck mexem em todos os postes.",
  floorToFloor: "De piso acabado a piso acabado. Se ainda falta acabamento, diga em Condições de obra.",
  fromEdge: "Recuo da borda aberta do piso até o poste.",
  gateDiagA: "De canto a canto oposto do vão. Diagonais iguais significam vão em esquadro.",
  gateDiagB: "A outra diagonal. Deve bater com a A.",
  gateDropRod: "Em portão de duas folhas, a tranca vertical que fixa a folha parada no chão.",
  gateFooting: "Profundidade da sapata. Abaixo da linha de gelo em portão de garagem.",
  gateGradeRise: "Percorra o caminho por onde o portão passa. Quanto o solo SOBE da posição fechada até totalmente aberto? Positivo se sobe, negativo se desce. É este número que decide se o portão trava.",
  gateGroundClearance: "Com o portão fechado, o vão embaixo da folha.",
  gateHeightHinge: "Do solo ao topo do poste do lado da dobradiça.",
  gateHeightLatch: "Do solo ao topo do poste do lado do trinco. Diferente do lado da dobradiça revela o desnível do vão.",
  gateHingeSide: "De fora, olhando para o portão, de que lado ficam as dobradiças.",
  gateHinges: "Tipo e quantas por folha.",
  gateInfill: "O que preenche a folha — balaústres, painel, tela.",
  gateLatch: "Como tranca, e se chaveia.",
  gateOpener: "Marca e modelo do motor, se houver.",
  gateOperation: "Como ele se move. Só portões que abrem girando recebem a checagem de folga no solo.",
  gatePicketSpacing: "Vão livre entre balaústres. Em portão de piscina, acima de 4 polegadas é reprovação direta.",
  gatePostMaterial: "Aço, madeira, pilar de alvenaria. Muda como as dobradiças são fixadas.",
  gatePostSize: "Dimensão do perfil dos postes, se forem novos ou se der para medir os existentes.",
  gatePower: "Já existe energia no portão, ou vai precisar puxar?",
  gateSafety: "Laços, fotocélulas, bordas de segurança — o que está instalado. Portão automatizado sem isso é risco.",
  gateSurface: "Por onde ele abre — asfalto, concreto, brita, grama. Brita se move e exige mais folga.",
  gateSwingDir: "Para que lado abre. Lembre: o portão que abre subindo é o que trava.",
  gateUse: "Para que serve o portão. Portão de piscina tem regra mais rígida que portão de serviço.",
  gateWidthBottom: "De poste a poste EMBAIXO. Raramente igual ao de cima — essa diferença é o motivo de às vezes uma folha quadrada não entrar.",
  gateWidthTop: "De poste a poste no ALTO do vão. Meça o vão livre, não o centro dos postes.",
  infillGap: "Meça do último balaústre até a FACE do acabamento na base da coluna — a superfície que mais avança. A ficha calcula o quanto o vão aumenta acima do acabamento, onde a coluna recua.",
  landingDiag: "De canto a canto oposto do patamar. Prova que está mesmo em esquadro antes de fabricar em ângulo reto.",
  landingNote: "Qualquer coisa do patamar que a oficina precise saber — obstruções, um degrau a menos, formato estranho.",
  length: "Comprimento na direção em que o corrimão corre.",
  matBottomRail: "Perfil do corrimão inferior, se houver.",
  matNotes: "Qualquer outra coisa que a oficina precise comprar ou saber.",
  matPicketSpacing: "Vão livre entre balaústres. Acima de 4 polegadas será sinalizado.",
  moldingHeightLbl: "Até que altura essa moldura sobe.",
  moldingLbl: "O quanto a moldura ou rodapé na base da coluna avança além da face dela.",
  mountType: "Como o poste fixa — furo no piso, placa de base por cima, ou lateral na longarina.",
  nominalRise: "O que o projeto ou o construtor diz que o espelho deveria ser. Os espelhos medidos são conferidos contra isso.",
  nominalRun: "O que o projeto diz que o piso deveria ser.",
  nosing: "O quanto o piso avança sobre o espelho de baixo.",
  notes: "Qualquer coisa que não coube em outro campo.",
  plumbLbl: "O quanto a coluna está fora de prumo na altura dela. Coluna torta muda todos os vãos em volta.",
  pointType: "O que existe neste ponto — poste novo, poste estrutural existente, parede de concreto ou clip.",
  postAnchors: "Padrão de chumbadores — quantos, que bitola.",
  postEdgeDist: "Do chumbador até a borda mais próxima do concreto ou pedra. Perto demais e estoura.",
  postPlate: "Dimensão da placa de base e em que posição fica.",
  postRefLbl: "Se suas medidas de poste são até o centro ou até a face. Errar isso move cada poste em meio poste.",
  postSetback: "Recuo do bico do degrau até o poste.",
  postSubstrate: "Espessura e condição daquilo em que você está fixando.",
  railHeight: "Da linha dos bicos (ou do piso, em trecho reto) até o topo do corrimão.",
  railKind: "Guarda-corpo impede queda, corrimão é o que se segura. Diga se este trecho precisa dos dois.",
  railSide: "De que lado fica o corrimão, de pé embaixo olhando para cima.",
  rakeLength: "Linha reta pelos bicos, do bico de baixo ao de cima. É a linha do corrimão — o número mais útil da ficha.",
  rampRunH: "Avanço horizontal da rampa — não o comprimento inclinado.",
  rampSlopeLen: "Comprimento medido pela própria superfície da rampa.",
  returnsLabel: "Como o corrimão termina — retorno na parede, ponta em laço, ou aberta.",
  rise: "Altura deste espelho — do topo de um piso ao topo do seguinte.",
  rotation: "Total de graus que a caracol gira de baixo para cima.",
  run: "Profundidade deste piso, do bico ao espelho. Meça na linha de caminhamento, não na ponta estreita.",
  segmentRise: "Altura total deste segmento.",
  segmentType: "O que é este pedaço do percurso — lance de escada, patamar, rampa ou curva.",
  skirtHeight: "Altura do rodapé ou moldura no poste.",
  spanName: "Nomeie esta peça de corrimão para a oficina casar com o desenho.",
  stairAngle: "Inclinação em relação à horizontal. Ponha um nível digital nos bicos. Conferida contra o espelho e o piso anotados.",
  stairSideLookingUp: "Qual lado, de pé embaixo da escada olhando para cima. Use sempre essa vista para esquerda e direita nunca inverterem.",
  stepsThisFlight: "Quantos pisos neste lance. Lembre que sempre há um espelho a mais que pisos.",
  topAdjustment: "Quanto o piso de cima vai mudar, mesma convenção.",
  topSpanLbl: "Comprimento livre desta peça no corrimão superior. É a medida de fabricação.",
  totalRise: "Do piso acabado de baixo ao piso acabado de cima, numa medida só. Os espelhos somados têm que dar isso.",
  totalRun: "Distância horizontal da face do primeiro espelho à face do último.",
  treadCovering: "O que vai sobre os pisos, se for o caso, e com que espessura.",
  bottomSurface: "Sobre o que a base do corrimão apoia HOJE — concreto, contrapiso, terra. Isso define a placa de base e o chumbador, então diga o que está lá agora, não o que vai virar.",
  topSurface: "Sobre o que o topo do corrimão apoia hoje, mesma ideia da base. Um corrimão fixado no contrapiso que depois recebe cerâmica fica curto.",
  futureTopping: "O que vai POR CIMA dessa superfície depois — cerâmica, pedra, madeira — e a espessura. Somamos no comprimento do poste agora para o corrimão ficar certo depois do acabamento.",
  orientationLbl: "Subindo a escada, qual lado tem parede. O lado da parede não leva guarda-corpo, então isso define o que fabricamos. Em escada que vira, cada lance é perguntado à parte — depois de 180° a mesma parede fica do outro lado.",
  treadsCount: "Quantos pisos tem a escada caracol.",
  turn: "Para que lado a escada vira depois deste patamar, se virar.",
  typicalRise: "A altura de espelho que a maioria dos degraus tem. Preencha uma vez, use Copiar para todos e corrija os diferentes.",
  typicalRun: "A profundidade que a maioria dos degraus tem. Preencha, copie e corrija os diferentes.",
  wallFinish: "Qual será o acabamento da parede onde o corrimão prende.",
  wellBandFrom: "Borda superior desta superfície, medida para baixo a partir do topo da parede do poço. Opcional.",
  wellBandLabel: "O que é esta superfície — acabamento, siding, fundação. Tudo por onde o guarda-corpo passa.",
  wellBandSetback: "Quanto esta superfície RECUA em relação à que mais avança. A que mais avança é 0.",
  wellBandTo: "Borda inferior desta superfície, mesma referência. Opcional.",
  wellConstruction: "Do que são feitas as paredes do poço. Concreto moldado e bloco recebem chumbadores de formas diferentes, e aço corrugado normalmente precisa de moldura em vez de parafusos.",
  wellDepth: "Do topo da parede do poço reto até o piso do poço. Acima de 44 polegadas, a saída exige escada.",
  wellDiagA: "De canto a canto oposto por dentro do poço. Tire as duas diagonais — se diferirem, o poço está fora de esquadro e uma grade retangular não vai encaixar.",
  wellDiagB: "A outra diagonal interna. Deve bater com a diagonal A.",
  wellGateHinge: "De que lado ficam as dobradiças.",
  wellGateLatch: "Como tranca. A ferragem de saída precisa abrir por dentro do poço sem chave e sem instrução.",
  wellGateSwing: "Para que lado o portão abre. Portão de saída deve abrir para fora do poço.",
  wellGateWidth: "Vão livre do portão já aberto — não a medida do marco.",
  wellGrateBearing: "Como a grade apoia: sobreposta no topo da parede, embutida nela, ou encaixada em moldura de cantoneira.",
  wellGrateInfill: "Do que a grade é feita e quão juntas ficam as barras — o vão entre barras também precisa barrar a esfera.",
  wellGrateLoad: "O que ela precisa aguentar. Diga se será pisada, ou se a carga de neve importa.",
  wellGuardHeight: "Do topo da parede do poço até o topo do guarda-corpo.",
  wellInsideLength: "Vão livre junto à casa, face a face por dentro do poço. É esta a medida de corte da grade.",
  wellInsideProjection: "Vão livre da fundação até a face interna da parede oposta.",
  wellLadderRungs: "Quantos degraus. A profundidade dividida pelo espaçamento, aproximadamente.",
  wellLadderSpacing: "Do centro de um degrau ao centro do seguinte. 18 polegadas é o máximo usual.",
  wellLadderStandoff: "Da face do degrau até a parede atrás dele — o espaço para a bota. Mínimo de 3 polegadas.",
  wellLadderTopExt: "Quanto os montantes sobem acima do topo da parede, para segurar na saída.",
  wellLadderWidth: "De fora a fora dos montantes da escada.",
  wellLengthAtHouse: "Junto à casa, face externa a face externa das paredes do poço. Meça no topo da parede, onde a grade ou o guarda-corpo vai apoiar.",
  wellMaxSphere: "A esfera que o fiscal usa. Normalmente 4 polegadas: nenhum vão pode deixar passar uma bola de 4 polegadas.",
  wellPostToWall: "O vão que você mediu da face do poste até a superfície que mais avança. A ficha calcula se isso deixa vão grande demais mais atrás.",
  wellProjection: "Reto a partir da parede da casa até a face externa da parede oposta do poço, no topo.",
  wellSillToFloor: "Do peitoril da janela até o piso do poço. Diz onde o topo da escada precisa chegar.",
  wellTopToGrade: "Quanto o topo da parede fica acima do terreno em volta. Use número negativo se a parede estiver abaixo do terreno.",
  wellWallRef: "Diga qual superfície MAIS avança em relação à casa — normalmente o acabamento na base do siding. Todas as outras são medidas recuando a partir dela.",
  wellWallThickness: "Largura do topo da parede do poço — a superfície onde a grade ou a placa de base realmente apoia.",
  wellWindowH: "Altura da janela do porão, de marco a marco.",
  wellWindowSwing: "Como a janela abre. Uma janela que abre para dentro do poço rouba o espaço que a escada precisa.",
  wellWindowW: "Largura da própria janela do porão, de marco a marco.",
  width: "Largura livre da escada, de face interna a face interna.",
  widthBottom: "Largura da escada medida embaixo.",
  widthMid: "Largura da escada medida no meio. Escada antiga raramente é paralela.",
  widthTop: "Largura da escada medida em cima.",
  winderRunIn: "Profundidade do piso na borda interna estreita do degrau em leque.",
  winderRunOut: "Profundidade do piso na borda externa larga.",
  winderTurn: "Quantos graus este degrau em leque gira a direção de caminhamento.",
};

const es: HelpDict = {
  alongPlatform: "Distancia a lo largo del descansillo, desde su inicio hasta este poste.",
  anchorInto: "En qué entra realmente el anclaje — granito, hormigón, madera, acero.",
  balAnchorType: "Lo que piensa usar — cuña, epoxi, perno pasante.",
  balCorners: "Esquinas del recorrido y con qué ángulo giran.",
  balDoorOpening: "En una julieta, el ancho del hueco de puerta que cierra.",
  balDrainage: "Gárgolas, desagües o pendiente que la barandilla y sus placas base deben salvar.",
  balEdgeCondition: "Estado del borde de la losa — desconchado, goterón, voladizo, armadura vista.",
  balEdgeDistance: "Del centro del anclaje al borde de la losa. Demasiado cerca y el borde revienta al apretar.",
  balEdgeLength: "El largo total del borde que llevará barandilla, de punta a punta.",
  balEmbedment: "Cuánto entra el anclaje en la losa. Esto más el recubrimiento de debajo debe caber en el espesor, o rompe por el fondo.",
  balFinishedFloor: "Cuál será el suelo cuando se instale la barandilla. Indique si falta una capa — cambia la altura del poste.",
  balGuardHeight: "Del suelo ACABADO a lo alto de la barandilla. Si aún va a ponerse baldosa o tarima, mida desde donde quedará el suelo, no desde donde está ahora.",
  balKind: "Un balcón que se pisa, o una julieta que solo cierra el hueco de la puerta.",
  balMinCover: "Cuánta losa maciza quiere dejar bajo el anclaje. Déjelo vacío si no hay especificación.",
  balMount: "Dónde apoyan los postes — sobre la losa, en su borde, perforado, o embebido.",
  balPicketSpacing: "Hueco libre entre balaustres. Por encima de 4 pulgadas se marcará.",
  balPlatePlan: "Tamaño de la placa base y el patrón de pernos.",
  balProjection: "Cuánto sobresale el balcón del edificio.",
  balReturns: "Cómo termina la barandilla en cada extremo — contra el muro, con retorno, o extremo libre.",
  balSlabMaterial: "Hormigón, chapa colaborante, estructura de madera. Decide qué anclaje sirve.",
  balSlabThickness: "Espesor de la losa en el borde. El anclaje debe caber dentro — sáquelo de un plano o de un taladro de prueba, no lo adivine.",
  bottomAdjustment: "Cuánto va a cambiar el suelo de abajo. Positivo si sube, negativo si baja.",
  brackets: "Cuántos soportes de pared y a qué separación.",
  clearWidth: "Ancho libre de paso, de la columna al pasamanos exterior.",
  clipDetail: "Cómo agarra el clip y sobre qué apoya.",
  color: "Color del acabado. Indique si debe igualar algo que ya está en obra.",
  columnDLbl: "Fondo de esa columna a la misma altura.",
  columnSize: "Diámetro de la columna central.",
  columnToPlatformEdge: "Distancia libre de la cara de la columna al borde del descansillo.",
  columnToWall: "Distancia libre de la cara de la columna al muro.",
  columnWLbl: "Ancho de la columna existente a la altura donde agarra el pasamanos — no en la base, que suele ser más ancha.",
  connAttachTo: "Dónde apoya este extremo — poste nuevo, muro, columna existente, suelo, otro vano, o nada.",
  connMaterial: "De qué está hecho eso. Decide si se puede soldar siquiera.",
  connMethod: "Cómo se fija a eso. La lista cambia para mostrar solo lo válido según lo elegido.",
  curveArc: "Largo medido por la propia curva. Se contrasta con radio y cuerda.",
  curveChord: "Línea recta de un extremo de la curva al otro.",
  curveRadius: "Radio al eje del pasamanos.",
  curveRise: "Altura total a lo largo de la curva. Déjelo vacío en curva llana.",
  curveSweep: "Total de grados que describe la curva.",
  depth: "Fondo del descansillo, de delante atrás.",
  diameter: "Diámetro total del caracol, de fuera a fuera.",
  distanceFromFirst: "Del borde de la primera huella al borde de la huella donde va este poste.",
  existingMaterial: "De qué es el poste existente. Solo el acero admite soldadura.",
  existingPostDepth: "Fondo de ese poste existente.",
  existingPostWidth: "Ancho de la cara del poste existente donde va a fijar.",
  extensions: "Prolongaciones de norma más allá de la primera y la última contrahuella, donde se exijan.",
  fenceEndTerm: "Contra qué termina.",
  fenceFooting: "Profundidad de las zapatas. Bajo la cota de helada.",
  fenceGates: "Cuántas puertas van en este tramo y más o menos dónde.",
  fenceHeight: "Altura de la valla, del suelo a lo alto del panel.",
  fencePanelWidth: "Ancho nominal de un panel o vano, si usa panel estándar.",
  fencePicketSpacing: "Hueco libre entre balaustres. Por encima de 4 pulgadas se marcará.",
  fencePostSize: "Dimensión del perfil de los postes.",
  fencePostSpacing: "De centro a centro entre postes.",
  fenceSegFollows: "Inclinar gira cada panel para seguir la pendiente. Escalonar mantiene los paneles a nivel y los baja por escalones. Cambia toda la fabricación de paneles.",
  fenceSegGrade: "Cuánto sube o baja el terreno a lo largo de este tramo.",
  fenceSegHeight: "Altura en este tramo, si difiere del resto.",
  fenceSegLength: "Largo SOLO de este tramo recto, de esquina a esquina.",
  fenceSegObstruction: "Árboles, roca, una losa, cualquier cosa en la línea aquí.",
  fenceSegPanels: "Cuántos paneles caben en este tramo.",
  fenceSegTurn: "Cuántos grados gira la valla al FINAL de este tramo. Déjelo vacío si sigue recto.",
  fenceStartTerm: "Contra qué empieza el tramo — esquina de la casa, valla existente, poste aislado.",
  fenceTotalRun: "Mida el tramo entero de punta a punta, de una vez, sin depender de los segmentos. La hoja comprueba que los segmentos sumen esto.",
  fenceUtilities: "Qué hay enterrado en la línea. Pida el marcado antes de que nadie excave una zapata.",
  finish: "Sistema de pintura. Por defecto pintura DTM estándar, salvo que pidieran galvanizado o pintura en polvo.",
  fireAccess: "Cómo llega el equipo. Ancho del callejón, si cabe andamio o plataforma, permiso para la acera.",
  fireAnchorCondition: "La unión con el edificio — lo que de verdad falla. Óxido que rezuma, mortero agrietado, movimiento.",
  fireAnchorCount: "Cuántos anclajes sujetan este nivel.",
  fireAnchorSpacing: "De centro a centro entre anclajes.",
  fireAnchorType: "Cómo se ata al edificio — perno pasante, anclaje de expansión, embebido. Diga lo que realmente se ve.",
  fireCondNotes: "Cualquier otra cosa que importe en este nivel.",
  fireCracks: "Soldadura agrietada, zanca partida, pieza fundida rota — dónde y de qué tamaño.",
  fireDeck: "Lo que se pisa — rejilla, chapa estriada, barra. Anote si está perforado en algún punto.",
  fireDeckCondition: "Estado de la rejilla o los peldaños. Agujeros, barra ausente, cualquier punto blando al pisar.",
  fireDeployed: "Con la escalera desplegada, cuánto queda todavía el peldaño más bajo sobre el suelo. Debería ser cero — lo que sobre es lo que alguien tendría que saltar.",
  fireFloorToFloor: "Del suelo de este balcón al del nivel inferior. Las contrahuellas de la escalera deben sumar exactamente esto.",
  fireGuardCondition: "Balaustres sueltos o ausentes, barandilla que se mueve al empujarla.",
  fireGuardHeight: "Del suelo a lo alto de la barandilla. 42 pulgadas es el mínimo actual para obra nueva; las escaleras antiguas suelen tener menos, y eso es lo que está registrando.",
  fireHeightGrade: "Del suelo de este balcón recto hasta el terreno.",
  fireLadderLength: "Largo total de la escalera en sí.",
  fireLadderOperates: "Pruébela. ¿Baja de verdad — libre, dura, o no baja?",
  fireLadderRung: "De centro a centro entre peldaños.",
  fireLadderType: "Deslizante, abatible, con contrapeso o fija. La fija nunca se mueve; las demás deberían.",
  fireLadderWidth: "De fuera a fuera de los largueros.",
  fireLandingSurface: "Dónde apoya al bajar — acera, césped, callejón, un tejado.",
  fireLoadTest: "Qué mostró la prueba de carga, o por qué no se hizo.",
  fireObstructions: "Qué estorba debajo. Condensadores, vallas, coches aparcados, plantas.",
  fireOpening: "Si este balcón sirve a una ventana o a una puerta.",
  fireOpeningW: "Ancho de la ventana o puerta a la que sirve este balcón.",
  firePaintSystem: "El recubrimiento existente y en qué estado está.",
  firePicketSpacing: "Hueco libre entre balaustres. Por encima de 4 pulgadas se marcará.",
  firePlatLength: "El balcón a lo largo del muro, de punta a punta.",
  firePlatWidth: "Cuánto sobresale el balcón del muro.",
  fireRating: "Su veredicto para este nivel: aprobado, vigilar o reprobado.",
  fireRust: "Dónde está el óxido y qué profundo. La costra superficial y la pérdida estructural son problemas distintos.",
  fireSectionLoss: "En el peor punto, cuánto acero falta ya. Mídalo con calibre si puede alcanzarlo.",
  fireSillToPlatform: "Del suelo del balcón al alféizar que hay que salvar. Un alféizar alto ya es una infracción de por sí.",
  fireStairAngle: "Inclinación respecto a la horizontal. Se contrasta con la contrahuella y la huella que acaba de anotar.",
  fireStairRise: "Altura de una contrahuella. Contrahuellas por esta medida debe dar el piso a piso de arriba.",
  fireStairRisers: "Cuente las contrahuellas, no las huellas. Siempre hay una contrahuella más que huellas.",
  fireStairRun: "Fondo de una huella, de delante atrás.",
  fireStairWidth: "Ancho libre entre zancas.",
  fireStories: "Cuántas plantas sirve esta escalera de incendios.",
  fireStowed: "Con la escalera recogida, a qué altura del suelo queda el peldaño más bajo.",
  fireTotalHeight: "Del suelo del balcón MÁS ALTO recto hasta el terreno. Se contrasta con las alturas piso a piso que anota en cada nivel.",
  fireViolations: "Copie lo que la notificación cita realmente, con sus palabras. Es lo que hay que subsanar.",
  fireWallMaterial: "Dónde entran los anclajes — ladrillo, bloque, hormigón, piedra o madera. El mortero viejo y blando cambia lo que va a aguantar.",
  flightCtrlRise: "Altura total SOLO de este tramo, medida aparte.",
  flightCtrlRun: "Avance total SOLO de este tramo, medido aparte.",
  flightRake: "De borde a borde SOLO de este tramo. Necesario por tramo cuando la escalera gira, porque un único valor global no verifica tramos en direcciones distintas.",
  floorChangeQuestion: "¿Va a cambiar la altura del suelo antes de instalar la barandilla? Baldosa, piedra o tarima nuevas mueven todos los postes.",
  floorToFloor: "De suelo acabado a suelo acabado. Si falta el acabado, dígalo en Condiciones de obra.",
  fromEdge: "Retranqueo desde el borde abierto de la huella al poste.",
  gateDiagA: "De esquina a esquina opuesta del hueco. Diagonales iguales significan hueco a escuadra.",
  gateDiagB: "La otra diagonal. Debe coincidir con la A.",
  gateDropRod: "En puerta de dos hojas, el pasador que fija al suelo la hoja que no se usa.",
  gateFooting: "Profundidad de la zapata. Bajo la cota de helada en puerta de entrada de coches.",
  gateGradeRise: "Recorra el camino que barre la puerta. ¿Cuánto SUBE el terreno desde cerrada hasta totalmente abierta? Positivo si sube, negativo si baja. Este número decide si la puerta se traba.",
  gateGroundClearance: "Con la puerta cerrada, el hueco bajo la hoja.",
  gateHeightHinge: "Del suelo a lo alto del poste del lado de la bisagra.",
  gateHeightLatch: "Del suelo a lo alto del poste del lado del cierre. Distinto del lado de la bisagra revela el desnivel del hueco.",
  gateHingeSide: "Desde fuera, mirando la puerta, de qué lado están las bisagras.",
  gateHinges: "Tipo y cuántas por hoja.",
  gateInfill: "Qué rellena la hoja — balaustres, panel, malla.",
  gateLatch: "Cómo cierra, y si lleva llave.",
  gateOpener: "Marca y modelo del motor, si lo hay.",
  gateOperation: "Cómo se mueve. Solo las abatibles reciben la comprobación de holgura sobre el terreno.",
  gatePicketSpacing: "Hueco libre entre balaustres. En puerta de piscina, más de 4 pulgadas es fallo directo.",
  gatePostMaterial: "Acero, madera, pilar de fábrica. Cambia cómo se fijan las bisagras.",
  gatePostSize: "Dimensión del perfil de los postes, si son nuevos o puede medir los existentes.",
  gatePower: "¿Ya hay corriente en la puerta, o hay que llevarla?",
  gateSafety: "Lazos, fotocélulas, bordes de seguridad — qué lleva instalado. Una puerta automática sin ellos es un riesgo.",
  gateSurface: "Sobre qué barre — asfalto, hormigón, grava, césped. La grava se mueve y pide más holgura.",
  gateSwingDir: "Hacia dónde abre. Recuerde: la que abre cuesta arriba es la que se traba.",
  gateUse: "Para qué es la puerta. Una de piscina tiene reglas más estrictas que una de servicio.",
  gateWidthBottom: "De poste a poste ABAJO. Rara vez igual que arriba — esa diferencia es por lo que a veces una hoja escuadrada no entra.",
  gateWidthTop: "De poste a poste ARRIBA del hueco. Mida el hueco libre, no los centros de los postes.",
  infillGap: "Mida del último balaustre a la CARA de la moldura al pie de la columna — la superficie que más sobresale. La hoja calcula cuánto crece el hueco por encima, donde la columna retrocede.",
  landingDiag: "De esquina a esquina opuesta del descansillo. Demuestra que está a escuadra antes de fabricar en ángulo recto.",
  landingNote: "Cualquier cosa del descansillo que el taller deba saber — obstrucciones, un escalón menos, forma rara.",
  length: "Largo en la dirección en que corre el pasamanos.",
  matBottomRail: "Perfil del pasamanos inferior, si lo hay.",
  matNotes: "Cualquier otra cosa que el taller deba pedir o saber.",
  matPicketSpacing: "Hueco libre entre balaustres. Por encima de 4 pulgadas se marcará.",
  moldingHeightLbl: "Hasta qué altura sube esa moldura.",
  moldingLbl: "Cuánto sobresale la moldura o zócalo del pie de la columna respecto a su cara.",
  mountType: "Cómo se fija el poste — taladrado en la huella, placa base encima, o lateral a la zanca.",
  nominalRise: "Lo que el plano o el constructor dice que debería ser la contrahuella. Las medidas se contrastan con esto.",
  nominalRun: "Lo que el plano dice que debería ser la huella.",
  nosing: "Cuánto vuela la huella sobre la contrahuella de abajo.",
  notes: "Cualquier cosa que no encaje en otra casilla.",
  plumbLbl: "Cuánto está la columna fuera de plomo en su altura. Una columna inclinada cambia todos los vanos alrededor.",
  pointType: "Qué hay en este punto — poste nuevo, poste estructural existente, muro de hormigón o clip.",
  postAnchors: "Patrón de anclajes — cuántos y de qué medida.",
  postEdgeDist: "Del anclaje al borde más cercano del hormigón o la piedra. Demasiado cerca y revienta.",
  postPlate: "Tamaño de la placa base y en qué posición va.",
  postRefLbl: "Si sus medidas de poste van al centro o a la cara. Equivocarse mueve cada poste medio poste.",
  postSetback: "Retranqueo desde el borde del peldaño al poste.",
  postSubstrate: "Espesor y estado de aquello donde fija.",
  railHeight: "De la línea de los bordes (o del suelo en tramo llano) a lo alto del pasamanos.",
  railKind: "La barandilla impide la caída, el pasamanos es lo que se agarra. Diga si este tramo necesita ambos.",
  railSide: "De qué lado va el pasamanos, de pie abajo mirando hacia arriba.",
  rakeLength: "Línea recta por los bordes, del de abajo al de arriba. Es la línea del pasamanos — el número más útil de la hoja.",
  rampRunH: "Avance horizontal de la rampa — no el largo inclinado.",
  rampSlopeLen: "Largo medido por la propia superficie de la rampa.",
  returnsLabel: "Cómo termina el pasamanos — retorno al muro, extremo en lazo, o abierto.",
  rise: "Altura de esta contrahuella — de lo alto de una huella a lo alto de la siguiente.",
  rotation: "Total de grados que gira el caracol de abajo arriba.",
  run: "Fondo de esta huella, del borde a la contrahuella. Mida en la línea de paso, no en el extremo estrecho.",
  segmentRise: "Altura total de este segmento.",
  segmentType: "Qué es este trozo del recorrido — tramo de escalera, descansillo, rampa o curva.",
  skirtHeight: "Altura del zócalo o moldura del poste.",
  spanName: "Nombre esta pieza de pasamanos para que el taller la case con el plano.",
  stairAngle: "Inclinación respecto a la horizontal. Ponga un nivel digital sobre los bordes. Se contrasta con la contrahuella y la huella anotadas.",
  stairSideLookingUp: "Qué lado, de pie al pie de la escalera mirando hacia arriba. Use siempre esa vista para que izquierda y derecha nunca se inviertan.",
  stepsThisFlight: "Cuántas huellas tiene este tramo. Recuerde que siempre hay una contrahuella más que huellas.",
  topAdjustment: "Cuánto va a cambiar el suelo de arriba, misma convención.",
  topSpanLbl: "Largo libre de esta pieza en el pasamanos superior. Es la medida de fabricación.",
  totalRise: "Del suelo acabado de abajo al de arriba, en una sola medida. Las contrahuellas sumadas deben dar esto.",
  totalRun: "Distancia horizontal de la cara de la primera contrahuella a la de la última.",
  treadCovering: "Qué va sobre las huellas, si algo, y con qué espesor.",
  bottomSurface: "Sobre qué apoya la base del pasamanos HOY — concreto, contrapiso, tierra. Define la placa base y el anclaje, así que diga lo que hay ahora, no lo que será.",
  topSurface: "Sobre qué apoya la parte alta hoy, igual que abajo. Un pasamanos fijado al contrapiso que luego recibe cerámica queda corto.",
  futureTopping: "Lo que irá ENCIMA de esa superficie después — cerámica, piedra, madera — y su espesor. Lo sumamos al largo del poste ahora para que quede bien tras el acabado.",
  orientationLbl: "Subiendo la escalera, qué lado tiene pared. El lado con pared no lleva barandilla, así que esto define lo que fabricamos. En escalera que gira, cada tramo se pregunta aparte — tras 180° la misma pared queda al otro lado.",
  treadsCount: "Cuántas huellas tiene la escalera de caracol.",
  turn: "Hacia dónde gira la escalera tras este descansillo, si gira.",
  typicalRise: "La altura de contrahuella que comparten casi todos los peldaños. Rellene una vez, use Copiar a todos y corrija los distintos.",
  typicalRun: "El fondo que comparten casi todos. Rellene, copie y corrija los distintos.",
  wallFinish: "Cuál será el acabado del muro donde agarra el pasamanos.",
  wellBandFrom: "Borde superior de esta superficie, medido hacia abajo desde arriba del muro. Opcional.",
  wellBandLabel: "Qué es esta superficie — moldura, revestimiento, cimientos. Todo por donde pasa la barandilla.",
  wellBandSetback: "Cuánto RETROCEDE esta superficie respecto a la que más sobresale. La que más sobresale es 0.",
  wellBandTo: "Borde inferior de esta superficie, misma referencia. Opcional.",
  wellConstruction: "De qué son los muros del foso. El hormigón vertido y el bloque reciben los anclajes de forma distinta, y el acero corrugado suele necesitar marco en vez de pernos.",
  wellDepth: "Desde arriba del muro recto hasta el suelo del foso. Por encima de 44 pulgadas la salida exige escalera.",
  wellDiagA: "De esquina a esquina opuesta por dentro. Tome las dos diagonales — si difieren el foso está fuera de escuadra y una rejilla rectangular no entrará.",
  wellDiagB: "La otra diagonal interior. Debe coincidir con la diagonal A.",
  wellGateHinge: "De qué lado van las bisagras.",
  wellGateLatch: "Cómo cierra. El herraje de salida debe abrirse desde dentro del foso sin llave y sin instrucciones.",
  wellGateSwing: "Hacia dónde abre la puerta. Las de salida deben abrir hacia fuera del foso.",
  wellGateWidth: "Luz libre de la puerta ya abierta — no la medida del marco.",
  wellGrateBearing: "Cómo apoya la rejilla: sobrepuesta encima del muro, embutida en él, o encajada en marco de angular.",
  wellGrateInfill: "De qué es la rejilla y qué separación llevan las barras — ese hueco también debe frenar la esfera.",
  wellGrateLoad: "Qué debe soportar. Indique si se pisa, o si importa la carga de nieve.",
  wellGuardHeight: "De arriba del muro del foso a lo alto de la barandilla.",
  wellInsideLength: "Luz libre junto a la casa, cara a cara por dentro del foso. Es la medida de corte de la rejilla.",
  wellInsideProjection: "Luz libre desde los cimientos hasta la cara interior del muro opuesto.",
  wellLadderRungs: "Cuántos peldaños. La profundidad dividida por la separación, aproximadamente.",
  wellLadderSpacing: "Del centro de un peldaño al centro del siguiente. 18 pulgadas es el máximo habitual.",
  wellLadderStandoff: "De la cara del peldaño al muro de detrás — el sitio para la bota. Mínimo 3 pulgadas.",
  wellLadderTopExt: "Cuánto suben los largueros por encima del muro, para agarrarse al salir.",
  wellLadderWidth: "De fuera a fuera de los largueros.",
  wellLengthAtHouse: "Junto a la casa, cara exterior a cara exterior de los muros. Mida arriba del muro, donde apoyará la rejilla o la barandilla.",
  wellMaxSphere: "La esfera que usa su inspector. Normalmente 4 pulgadas: ningún hueco puede dejar pasar una bola de 4 pulgadas.",
  wellPostToWall: "El hueco que midió de la cara del poste a la superficie que más sobresale. La hoja calcula si eso deja un hueco excesivo más atrás.",
  wellProjection: "Recto desde el muro de la casa hasta la cara exterior del muro opuesto, arriba.",
  wellSillToFloor: "Del alféizar al suelo del foso. Indica dónde debe llegar la parte alta de la escalera.",
  wellTopToGrade: "Cuánto sobresale el muro sobre el terreno. Ponga número negativo si queda por debajo.",
  wellWallRef: "Diga qué superficie sobresale MÁS respecto a la casa — normalmente la moldura al pie del revestimiento. Las demás se miden retrocediendo desde ella.",
  wellWallThickness: "Ancho de la parte alta del muro — la superficie donde apoya realmente la rejilla o la placa base.",
  wellWindowH: "Alto de la ventana del sótano, de marco a marco.",
  wellWindowSwing: "Cómo abre la ventana. Una que abre hacia el foso quita el espacio que necesita la escalera.",
  wellWindowW: "Ancho de la ventana del sótano, de marco a marco.",
  width: "Ancho libre de la escalera, de cara interior a cara interior.",
  widthBottom: "Ancho medido abajo.",
  widthMid: "Ancho medido en el medio. Una escalera vieja rara vez es paralela.",
  widthTop: "Ancho de la escalera medido arriba.",
  winderRunIn: "Fondo de la huella en el borde interior estrecho del peldaño en abanico.",
  winderRunOut: "Fondo en el borde exterior ancho.",
  winderTurn: "Cuántos grados gira este peldaño en abanico la dirección de paso.",
};


const HELP: Record<string, HelpDict> = { en, pt, es };

/** The explanation for a field, or null when it has none yet. */
export function helpText(lang: string, key: string): string | null {
  const dict = HELP[lang] || HELP.en;
  return dict[key] ?? HELP.en[key] ?? null;
}

/** Keys that still have no explanation — used by the coverage test. */
export function missingHelp(keys: string[]): string[] {
  return keys.filter((k) => !HELP.en[k]);
}
