"use client";
import { useState } from "react";
import Link from "next/link";
import { projectMoney, type MoneyJob, type MoneyScope } from "@/lib/shop/project-money";
export default function ProjectMoney({ jobs, lang }: { jobs: MoneyJob[] | null; lang: string }) {
  const [scope, setScope] = useState<MoneyScope>("current");
  const label = (en: string, pt: string, es: string) => lang === "pt" ? pt : lang === "es" ? es : en;
  const money = (n: number | null) => n === null ? "—" : n.toLocaleString(lang === "pt" ? "pt-BR" : lang === "es" ? "es-US" : "en-US", { style: "currency", currency: "USD" });
  if (!jobs) return <div role="alert" className="mb-4 rounded-2xl border border-amber-700 bg-amber-950/30 p-4">{label("Could not load project money. Refresh to try again.", "Não foi possível carregar os valores. Atualize para tentar novamente.", "No se pudieron cargar los importes. Actualiza para intentarlo de nuevo.")}</div>;
  const summary = projectMoney(jobs, scope);
  const labels = { current: label("All current jobs", "Todas as obras atuais", "Todos los proyectos actuales"), active: label("Active only", "Somente ativas", "Solo activos"), archived: label("Archived records", "Registros arquivados", "Registros archivados") };
  return <section className="mb-4 rounded-2xl border border-emerald-800/70 bg-emerald-950/30 p-4" aria-label={label("Project money", "Valores das obras", "Importes de proyectos")}>
    <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold text-emerald-400">{label("Project money", "Valores das obras", "Importes de proyectos")}</h2><select aria-label={label("Money summary scope", "Abrangência do resumo", "Alcance del resumen")} value={scope} onChange={e => setScope(e.target.value as MoneyScope)} className="min-h-12 max-w-full rounded-xl border border-white/15 bg-neutral-950 px-3 text-sm">{Object.entries(labels).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div>
    <p className="my-3 text-xs leading-relaxed text-neutral-400">{scope === "archived" ? label("Historical records for review. May include unsigned, merged or cancelled work; kept separate from current totals.", "Histórico para revisão. Pode incluir propostas não assinadas e obras mescladas ou canceladas; separado dos totais atuais.", "Historial para revisión. Puede incluir trabajo sin firmar, fusionado o cancelado; separado de los totales actuales.") : scope === "current" ? label("Active and completed jobs. Sales leads and archived records are excluded. Search and board filters do not change these totals.", "Obras ativas e concluídas. Oportunidades e registros arquivados não entram. A busca e os filtros não alteram os totais.", "Proyectos activos y terminados. Excluye oportunidades y registros archivados. La búsqueda y filtros no cambian estos totales.") : label("Active jobs only; completed jobs are excluded.", "Somente obras ativas; concluídas não entram.", "Solo proyectos activos; excluye los terminados.")}</p>
    <dl className="grid grid-cols-3 gap-1.5 sm:gap-2">{[[label("Project total", "Total das obras", "Total de proyectos"), summary.total], [label("Money received", "Dinheiro recebido", "Dinero recibido"), summary.received], [label("Balance due", "Saldo a receber", "Saldo pendiente"), summary.balance]].map(([name, value]) => <div key={name} className="min-w-0 rounded-xl bg-neutral-950/40 px-1.5 py-3 sm:p-3"><dt className="min-h-8 text-[11px] leading-4 text-neutral-400 sm:min-h-0 sm:text-xs">{name}</dt><dd className="mt-1 whitespace-nowrap text-[11px] font-bold tabular-nums tracking-tight text-neutral-100 min-[375px]:text-xs min-[440px]:text-sm sm:text-lg">{money(value as number)}</dd></div>)}</dl>
    {summary.estimatesToReview > 0 && <div role="status" className="mt-3 rounded-xl border border-amber-500/40 bg-amber-500/10 p-3 text-sm text-amber-300"><strong>{label("Provisional totals — estimates need review", "Totais provisórios — revise os orçamentos", "Totales provisionales — revisa los presupuestos")}</strong><p className="mt-1">{label("Some estimates may be missing from the recorded contract amounts. Open each job to mark the estimate as additional, already included, or excluded.", "Alguns orçamentos podem não estar nos valores registrados. Abra cada obra para classificá-los como adicionais, já incluídos ou excluídos.", "Algunos presupuestos pueden faltar en los importes registrados. Abre cada proyecto y clasifícalos como adicionales, ya incluidos o excluidos.")}</p><ul className="mt-2 space-y-2">{summary.rows.filter(r => r.estimatesToReview > 0).map(r => <li key={r.id}><Link className="inline-block py-1 font-bold underline" href={`/shop/job/${r.id}`}>{r.number} · {r.customer} ({r.estimatesToReview})</Link></li>)}</ul></div>}
    {(summary.missingTotals > 0 || summary.missingPayments > 0) && <p role="status" className="mt-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-3 text-sm text-amber-300">{label("Incomplete records", "Registros incompletos", "Registros incompletos")}: {summary.missingTotals} {label("missing job amounts", "sem valor da obra", "sin importe del proyecto")}; {summary.missingPayments} {label("missing payment amounts", "sem valor recebido", "sin importe recibido")}. {label("Totals include known amounts only. A balance is counted only when both amounts are recorded.", "Totais incluem apenas valores conhecidos. O saldo entra apenas quando os dois valores estão registrados.", "Los totales incluyen solo importes conocidos. El saldo cuenta solo cuando ambos importes están registrados.")}</p>}
    {summary.credit > 0 && <p className="mt-3 text-sm text-amber-300">{label("Payments above job value", "Pagamentos acima do valor da obra", "Pagos superiores al importe")}: {money(summary.credit)}. {label("These do not reduce other jobs’ balances.", "Não reduzem o saldo de outras obras.", "No reducen los saldos de otros proyectos.")}</p>}
    <details className="mt-3"><summary className="cursor-pointer py-3 text-sm font-semibold text-emerald-300">{summary.rows.length} {label("jobs · View breakdown", "obras · Ver detalhes", "proyectos · Ver detalle")}</summary><div className="max-h-96 overflow-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr className="text-xs text-neutral-400"><th className="p-2">{label("Job", "Obra", "Proyecto")}</th><th className="p-2">{label("Total", "Total", "Total")}</th><th className="p-2">{label("Received", "Recebido", "Recibido")}</th><th className="p-2">{label("Balance", "Saldo", "Saldo")}</th></tr></thead><tbody>{summary.rows.map(row => <tr key={row.id} className="border-t border-white/10"><td className="p-2"><Link className="block py-2 text-amber-300 underline" href={`/shop/job/${row.id}`}>{row.number} · {row.customer}</Link></td><td className="p-2">{money(row.total)}</td><td className="p-2">{money(row.received)}</td><td className="p-2">{money(row.balance)}</td></tr>)}</tbody></table></div></details>
  </section>;
}
