"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { Worker } from "@/lib/shop/shared";
import { t } from "@/lib/shop/i18n";

export default function ProfileForm({ profile, lang }: { profile: Worker; lang: string }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ name: profile.name, phone: profile.phone || "", email: profile.email || "", lang: profile.lang || "en", emergencyContactName: profile.emergency_contact_name || "", emergencyContactPhone: profile.emergency_contact_phone || "" });
  const field = (key: keyof typeof form, label: string, type = "text") => <label className="block"><span className="mb-1.5 block text-sm text-neutral-400">{label}</span><input type={type} value={form[key]} onChange={e => setForm({ ...form, [key]: e.target.value })} className="min-h-14 w-full rounded-2xl border border-white/10 bg-neutral-900 px-4 outline-none focus:border-amber-500" /></label>;
  async function save() { setBusy(true); setSaved(false); setError(""); try { const r = await fetch("/shop/api/action", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "profile_update", ...form }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Could not save"); setSaved(true); router.refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save"); } finally { setBusy(false); } }
  return <div className="space-y-6"><section className="space-y-4 rounded-[24px] border border-white/10 bg-neutral-900/60 p-5"><h2 className="text-lg font-semibold">{t(lang, "personalInfo")}</h2>{field("name", t(lang, "fullName"))}{field("phone", t(lang, "phone"), "tel")}{field("email", t(lang, "email"), "email")}<label className="block"><span className="mb-1.5 block text-sm text-neutral-400">{t(lang, "preferredLanguage")}</span><select value={form.lang} onChange={e => setForm({ ...form, lang: e.target.value })} className="min-h-14 w-full rounded-2xl border border-white/10 bg-neutral-900 px-4"><option value="en">English</option><option value="pt">Português</option><option value="es">Español</option></select></label></section><section className="space-y-4 rounded-[24px] border border-white/10 bg-neutral-900/60 p-5"><div><h2 className="text-lg font-semibold">{t(lang, "emergencyContact")}</h2><p className="text-sm text-neutral-500">{t(lang, "emergencyHint")}</p></div>{field("emergencyContactName", t(lang, "contactName"))}{field("emergencyContactPhone", t(lang, "contactPhone"), "tel")}</section>{error && <p className="text-sm text-red-400">{error}</p>}{saved && <p className="text-sm text-emerald-400">{t(lang, "profileSaved")}</p>}<button disabled={busy || !form.name.trim()} onClick={save} className="min-h-14 w-full rounded-2xl bg-amber-500 text-lg font-bold text-black disabled:opacity-40">{busy ? t(lang, "saving") : t(lang, "saveChanges")}</button><p className="text-center text-xs text-neutral-600">{t(lang, "profileAdminNote")}</p></div>;
}
