"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Check, Download, MapPin, PencilLine, X } from "lucide-react";
import { t } from "@/lib/shop/i18n";
import { fmtDateTime, fromShopInput, hoursToHm, toShopInput } from "@/lib/shop/shared";

export type ShiftRow = { id:string; worker:string; startedAt:string; endedAt:string|null; hours:number; regular:number; overtime:number; status:string; startLat:number|null; startLng:number|null; endLat:number|null; endLng:number|null };
export type CorrectionRow = { id:string; shiftId:string; worker:string; reason:string; status:string; createdAt:string };
const dt = (s:string|null, lang:string) => s ? fmtDateTime(s, lang) : t(lang,"running");
const localInput = (s:string|null) => s ? toShopInput(s) : "";

export default function TimesheetClient({ shifts, corrections=[], admin=false, lang="en" }:{ shifts:ShiftRow[]; corrections?:CorrectionRow[]; admin?:boolean; lang?:string }) {
  const router=useRouter(); const [,transition]=useTransition(); const [edit,setEdit]=useState<ShiftRow|null>(null); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [start,setStart]=useState(""); const [end,setEnd]=useState("");
  async function act(payload:Record<string,unknown>){setBusy(true);try{const r=await fetch("/shop/api/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw new Error((await r.json()).error);setEdit(null);transition(()=>router.refresh());}finally{setBusy(false)}}
  function csv(){const rows=[["Employee","Clock in","Clock out","Regular","Overtime","Total","Total (h:mm)","Status"],...shifts.map(s=>[s.worker,s.startedAt,s.endedAt||"",s.regular.toFixed(2),s.overtime.toFixed(2),s.hours.toFixed(2),hoursToHm(s.hours),s.status])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`kiw-timesheet-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
  return <div className="space-y-5">
    {admin&&<button onClick={csv} className="flex min-h-12 items-center gap-2 rounded-full bg-white px-5 font-semibold text-black"><Download className="h-4 w-4"/>{t(lang,"exportCsv")}</button>}
    <section className="overflow-hidden rounded-[22px] border border-white/10 bg-neutral-900/60">{shifts.length?shifts.map(s=><div key={s.id} className="border-b border-white/5 p-4 last:border-0"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{admin?s.worker:dt(s.startedAt,lang).split(",")[0]}</div><div className="mt-0.5 text-sm text-neutral-500">{dt(s.startedAt,lang)} → {dt(s.endedAt,lang)}</div></div><div className="text-right"><div className="text-lg font-semibold tabular-nums">{hoursToHm(s.hours)}</div><div className={`text-xs ${s.status==="approved"?"text-emerald-400":"text-neutral-500"}`}>{s.status}</div></div></div>
      {s.overtime>0&&<div className="mt-2 text-sm text-amber-400">{hoursToHm(s.regular)} {t(lang,"regular")} · {hoursToHm(s.overtime)} {t(lang,"overtime")}</div>}
      <div className="mt-3 flex items-center gap-2">{s.startLat!=null&&<a target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${s.startLat},${s.startLng}`} className="flex items-center gap-1 text-xs text-blue-400"><MapPin className="h-3.5 w-3.5"/>{t(lang,"mapStart")}</a>}{s.endLat!=null&&<a target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${s.endLat},${s.endLng}`} className="flex items-center gap-1 text-xs text-blue-400"><MapPin className="h-3.5 w-3.5"/>{t(lang,"mapEnd")}</a>}
      {!admin&&s.endedAt&&<button onClick={()=>{setEdit(s);setStart(localInput(s.startedAt));setEnd(localInput(s.endedAt))}} className="ml-auto flex items-center gap-1 text-xs text-amber-400"><PencilLine className="h-3.5 w-3.5"/>{t(lang,"requestCorrection")}</button>}
      {admin&&s.endedAt&&<button disabled={busy} onClick={()=>{setEdit(s);setStart(localInput(s.startedAt));setEnd(localInput(s.endedAt))}} className="ml-auto flex items-center gap-1 text-xs text-amber-400"><PencilLine className="h-3.5 w-3.5"/>{t(lang,"editTimes")}</button>}
      {admin&&s.endedAt&&s.status!=="approved"&&<><button disabled={busy} onClick={()=>act({type:"shift_review",shiftId:s.id,status:"approved"})} className="flex items-center gap-1 text-xs text-emerald-400"><Check className="h-4 w-4"/>{t(lang,"approve")}</button><button disabled={busy} onClick={()=>act({type:"shift_review",shiftId:s.id,status:"rejected"})} className="flex items-center gap-1 text-xs text-red-400"><X className="h-4 w-4"/>{t(lang,"reject")}</button></>}</div></div>):<p className="p-8 text-center text-sm text-neutral-500">{t(lang,"noShifts")}</p>}</section>
    {corrections.length>0&&<section><h2 className="mb-2 text-lg font-semibold">{t(lang,"correctionRequests")}</h2><div className="space-y-2">{corrections.map(c=><div key={c.id} className="rounded-2xl border border-white/10 bg-neutral-900 p-4"><div className="flex justify-between"><div className="font-semibold">{c.worker}</div><div className="text-xs text-neutral-500">{c.status}</div></div><p className="mt-1 text-sm text-neutral-400">{c.reason}</p>{admin&&c.status==="pending"&&<div className="mt-3 flex gap-2"><button onClick={()=>act({type:"correction_review",id:c.id,status:"approved"})} className="rounded-full bg-emerald-500 px-4 py-2 text-sm font-semibold text-black">{t(lang,"approve")}</button><button onClick={()=>act({type:"correction_review",id:c.id,status:"rejected"})} className="rounded-full bg-neutral-800 px-4 py-2 text-sm">{t(lang,"reject")}</button></div>}</div>)}</div></section>}
    {edit&&<div className="fixed inset-0 z-[60] flex items-end bg-black/70" onClick={()=>setEdit(null)}><div className="w-full rounded-t-[28px] bg-neutral-900 p-5 pb-8" onClick={e=>e.stopPropagation()}><h2 className="text-xl font-semibold">{t(lang,"correctionTitle")}</h2><label className="mt-4 block text-sm text-neutral-400">{t(lang,"clockInLabel")}</label><input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 min-h-12 w-full rounded-xl bg-neutral-800 px-3"/><label className="mt-3 block text-sm text-neutral-400">{t(lang,"clockOutLabel")}</label><input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 min-h-12 w-full rounded-xl bg-neutral-800 px-3"/><label className="mt-3 block text-sm text-neutral-400">{t(lang,"correctionReason")}</label><textarea value={reason} onChange={e=>setReason(e.target.value)} className="mt-1 min-h-24 w-full rounded-xl bg-neutral-800 p-3"/><button disabled={busy||(!admin&&reason.trim().length<3)} onClick={()=>act(admin?{type:"shift_edit",shiftId:edit.id,startedAt:fromShopInput(start),endedAt:fromShopInput(end),note:reason}:{type:"time_correction_request",shiftId:edit.id,startedAt:fromShopInput(start),endedAt:fromShopInput(end),reason})} className="mt-4 min-h-14 w-full rounded-2xl bg-amber-500 font-bold text-black disabled:opacity-40">{admin?t(lang,"saveTimes"):t(lang,"sendRequest")}</button></div></div>}
  </div>;
}
